/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.gtfs.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Agency service. Represents a row in the &quot;gtfs_Agency&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link eu.strasbourg.service.gtfs.model.impl.AgencyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link eu.strasbourg.service.gtfs.model.impl.AgencyImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see Agency
 * @see eu.strasbourg.service.gtfs.model.impl.AgencyImpl
 * @see eu.strasbourg.service.gtfs.model.impl.AgencyModelImpl
 * @generated
 */
@ProviderType
public interface AgencyModel extends BaseModel<Agency> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a agency model instance should use the {@link Agency} interface instead.
	 */

	/**
	 * Returns the primary key of this agency.
	 *
	 * @return the primary key of this agency
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this agency.
	 *
	 * @param primaryKey the primary key of this agency
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this agency.
	 *
	 * @return the uuid of this agency
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this agency.
	 *
	 * @param uuid the uuid of this agency
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this agency.
	 *
	 * @return the ID of this agency
	 */
	public long getId();

	/**
	 * Sets the ID of this agency.
	 *
	 * @param id the ID of this agency
	 */
	public void setId(long id);

	/**
	 * Returns the agency_name of this agency.
	 *
	 * @return the agency_name of this agency
	 */
	@AutoEscape
	public String getAgency_name();

	/**
	 * Sets the agency_name of this agency.
	 *
	 * @param agency_name the agency_name of this agency
	 */
	public void setAgency_name(String agency_name);

	/**
	 * Returns the agency_url of this agency.
	 *
	 * @return the agency_url of this agency
	 */
	@AutoEscape
	public String getAgency_url();

	/**
	 * Sets the agency_url of this agency.
	 *
	 * @param agency_url the agency_url of this agency
	 */
	public void setAgency_url(String agency_url);

	/**
	 * Returns the agency_timezone of this agency.
	 *
	 * @return the agency_timezone of this agency
	 */
	@AutoEscape
	public String getAgency_timezone();

	/**
	 * Sets the agency_timezone of this agency.
	 *
	 * @param agency_timezone the agency_timezone of this agency
	 */
	public void setAgency_timezone(String agency_timezone);

	/**
	 * Returns the agency_phone of this agency.
	 *
	 * @return the agency_phone of this agency
	 */
	@AutoEscape
	public String getAgency_phone();

	/**
	 * Sets the agency_phone of this agency.
	 *
	 * @param agency_phone the agency_phone of this agency
	 */
	public void setAgency_phone(String agency_phone);

	/**
	 * Returns the agency_fare_url of this agency.
	 *
	 * @return the agency_fare_url of this agency
	 */
	@AutoEscape
	public String getAgency_fare_url();

	/**
	 * Sets the agency_fare_url of this agency.
	 *
	 * @param agency_fare_url the agency_fare_url of this agency
	 */
	public void setAgency_fare_url(String agency_fare_url);

	/**
	 * Returns the agency_lang of this agency.
	 *
	 * @return the agency_lang of this agency
	 */
	@AutoEscape
	public String getAgency_lang();

	/**
	 * Sets the agency_lang of this agency.
	 *
	 * @param agency_lang the agency_lang of this agency
	 */
	public void setAgency_lang(String agency_lang);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(eu.strasbourg.service.gtfs.model.Agency agency);

	@Override
	public int hashCode();

	@Override
	public CacheModel<eu.strasbourg.service.gtfs.model.Agency> toCacheModel();

	@Override
	public eu.strasbourg.service.gtfs.model.Agency toEscapedModel();

	@Override
	public eu.strasbourg.service.gtfs.model.Agency toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}