/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.gtfs.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CacheHoursJSON service. Represents a row in the &quot;gtfs_CacheHoursJSON&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>eu.strasbourg.service.gtfs.model.impl.CacheHoursJSONModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>eu.strasbourg.service.gtfs.model.impl.CacheHoursJSONImpl</code>.
 * </p>
 *
 * @author Cedric Henry
 * @see CacheHoursJSON
 * @generated
 */
@ProviderType
public interface CacheHoursJSONModel extends BaseModel<CacheHoursJSON> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cache hours json model instance should use the {@link CacheHoursJSON} interface instead.
	 */

	/**
	 * Returns the primary key of this cache hours json.
	 *
	 * @return the primary key of this cache hours json
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this cache hours json.
	 *
	 * @param primaryKey the primary key of this cache hours json
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this cache hours json.
	 *
	 * @return the uuid of this cache hours json
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this cache hours json.
	 *
	 * @param uuid the uuid of this cache hours json
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the stop code of this cache hours json.
	 *
	 * @return the stop code of this cache hours json
	 */
	@AutoEscape
	public String getStopCode();

	/**
	 * Sets the stop code of this cache hours json.
	 *
	 * @param stopCode the stop code of this cache hours json
	 */
	public void setStopCode(String stopCode);

	/**
	 * Returns the json hour of this cache hours json.
	 *
	 * @return the json hour of this cache hours json
	 */
	@AutoEscape
	public String getJsonHour();

	/**
	 * Sets the json hour of this cache hours json.
	 *
	 * @param jsonHour the json hour of this cache hours json
	 */
	public void setJsonHour(String jsonHour);

	/**
	 * Returns the creation date of this cache hours json.
	 *
	 * @return the creation date of this cache hours json
	 */
	public Date getCreationDate();

	/**
	 * Sets the creation date of this cache hours json.
	 *
	 * @param creationDate the creation date of this cache hours json
	 */
	public void setCreationDate(Date creationDate);

	/**
	 * Returns the modified date of this cache hours json.
	 *
	 * @return the modified date of this cache hours json
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cache hours json.
	 *
	 * @param modifiedDate the modified date of this cache hours json
	 */
	public void setModifiedDate(Date modifiedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		eu.strasbourg.service.gtfs.model.CacheHoursJSON cacheHoursJSON);

	@Override
	public int hashCode();

	@Override
	public CacheModel<eu.strasbourg.service.gtfs.model.CacheHoursJSON>
		toCacheModel();

	@Override
	public eu.strasbourg.service.gtfs.model.CacheHoursJSON toEscapedModel();

	@Override
	public eu.strasbourg.service.gtfs.model.CacheHoursJSON toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}