# Image sur laquelle se base les opérations suivantes (@see https://hub.docker.com/r/liferay/dxp)
FROM liferay/dxp:7.2.10-dxp-4

# Changement d'utilisateur pour root (évite le problème de permission sur les fichiers déposés dans le conteneur)
USER root