/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.place.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CacheJson service. Represents a row in the &quot;place_CacheJson&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>eu.strasbourg.service.place.model.impl.CacheJsonModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>eu.strasbourg.service.place.model.impl.CacheJsonImpl</code>.
 * </p>
 *
 * @author Angelique Zunino Champougny
 * @see CacheJson
 * @generated
 */
@ProviderType
public interface CacheJsonModel extends BaseModel<CacheJson> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cache json model instance should use the {@link CacheJson} interface instead.
	 */

	/**
	 * Returns the primary key of this cache json.
	 *
	 * @return the primary key of this cache json
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this cache json.
	 *
	 * @param primaryKey the primary key of this cache json
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this cache json.
	 *
	 * @return the uuid of this cache json
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this cache json.
	 *
	 * @param uuid the uuid of this cache json
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the sig ID of this cache json.
	 *
	 * @return the sig ID of this cache json
	 */
	@AutoEscape
	public String getSigId();

	/**
	 * Sets the sig ID of this cache json.
	 *
	 * @param sigId the sig ID of this cache json
	 */
	public void setSigId(String sigId);

	/**
	 * Returns the json lieu of this cache json.
	 *
	 * @return the json lieu of this cache json
	 */
	@AutoEscape
	public String getJsonLieu();

	/**
	 * Sets the json lieu of this cache json.
	 *
	 * @param jsonLieu the json lieu of this cache json
	 */
	public void setJsonLieu(String jsonLieu);

	/**
	 * Returns the json horaire of this cache json.
	 *
	 * @return the json horaire of this cache json
	 */
	@AutoEscape
	public String getJsonHoraire();

	/**
	 * Sets the json horaire of this cache json.
	 *
	 * @param jsonHoraire the json horaire of this cache json
	 */
	public void setJsonHoraire(String jsonHoraire);

	/**
	 * Returns the create place of this cache json.
	 *
	 * @return the create place of this cache json
	 */
	public Date getCreatePlace();

	/**
	 * Sets the create place of this cache json.
	 *
	 * @param createPlace the create place of this cache json
	 */
	public void setCreatePlace(Date createPlace);

	/**
	 * Returns the modified place of this cache json.
	 *
	 * @return the modified place of this cache json
	 */
	public Date getModifiedPlace();

	/**
	 * Sets the modified place of this cache json.
	 *
	 * @param modifiedPlace the modified place of this cache json
	 */
	public void setModifiedPlace(Date modifiedPlace);

	/**
	 * Returns the is active of this cache json.
	 *
	 * @return the is active of this cache json
	 */
	public boolean getIsActive();

	/**
	 * Returns <code>true</code> if this cache json is is active.
	 *
	 * @return <code>true</code> if this cache json is is active; <code>false</code> otherwise
	 */
	public boolean isIsActive();

	/**
	 * Sets whether this cache json is is active.
	 *
	 * @param isActive the is active of this cache json
	 */
	public void setIsActive(boolean isActive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(eu.strasbourg.service.place.model.CacheJson cacheJson);

	@Override
	public int hashCode();

	@Override
	public CacheModel<eu.strasbourg.service.place.model.CacheJson>
		toCacheModel();

	@Override
	public eu.strasbourg.service.place.model.CacheJson toEscapedModel();

	@Override
	public eu.strasbourg.service.place.model.CacheJson toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}