/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.project.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.project.model.BudgetParticipatif;
import eu.strasbourg.service.project.model.BudgetParticipatifModel;
import eu.strasbourg.service.project.model.BudgetParticipatifSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BudgetParticipatif service. Represents a row in the &quot;project_BudgetParticipatif&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>BudgetParticipatifModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BudgetParticipatifImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see BudgetParticipatifImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class BudgetParticipatifModelImpl
	extends BaseModelImpl<BudgetParticipatif>
	implements BudgetParticipatifModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a budget participatif model instance should use the <code>BudgetParticipatif</code> interface instead.
	 */
	public static final String TABLE_NAME = "project_BudgetParticipatif";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"budgetParticipatifId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"title", Types.VARCHAR}, {"description", Types.CLOB},
		{"summary", Types.VARCHAR}, {"budget", Types.VARCHAR},
		{"motif", Types.CLOB}, {"placeTextArea", Types.VARCHAR},
		{"inTheNameOf", Types.VARCHAR}, {"citoyenLastname", Types.VARCHAR},
		{"citoyenFirstname", Types.VARCHAR}, {"citoyenAdresse", Types.VARCHAR},
		{"citoyenPostalCode", Types.BIGINT}, {"citoyenCity", Types.VARCHAR},
		{"citoyenPhone", Types.VARCHAR}, {"citoyenMobile", Types.VARCHAR},
		{"citoyenEmail", Types.VARCHAR}, {"citoyenBirthday", Types.TIMESTAMP},
		{"hasCopyright", Types.BOOLEAN}, {"videoUrl", Types.VARCHAR},
		{"imageTimeline", Types.BIGINT}, {"opacityImage", Types.DOUBLE},
		{"isCrush", Types.BOOLEAN}, {"crushComment", Types.CLOB},
		{"publikId", Types.VARCHAR}, {"imageId", Types.BIGINT},
		{"filesIds", Types.VARCHAR}, {"budgetPhaseId", Types.BIGINT},
		{"parentId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("budgetParticipatifId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.CLOB);
		TABLE_COLUMNS_MAP.put("summary", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("budget", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("motif", Types.CLOB);
		TABLE_COLUMNS_MAP.put("placeTextArea", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("inTheNameOf", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenLastname", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenFirstname", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenAdresse", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenPostalCode", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("citoyenCity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenPhone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenMobile", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("citoyenBirthday", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("hasCopyright", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("videoUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageTimeline", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("opacityImage", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("isCrush", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("crushComment", Types.CLOB);
		TABLE_COLUMNS_MAP.put("publikId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("filesIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("budgetPhaseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table project_BudgetParticipatif (uuid_ VARCHAR(75) null,budgetParticipatifId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,title VARCHAR(400) null,description TEXT null,summary VARCHAR(400) null,budget VARCHAR(75) null,motif TEXT null,placeTextArea VARCHAR(400) null,inTheNameOf VARCHAR(400) null,citoyenLastname VARCHAR(75) null,citoyenFirstname VARCHAR(75) null,citoyenAdresse VARCHAR(400) null,citoyenPostalCode LONG,citoyenCity VARCHAR(400) null,citoyenPhone VARCHAR(75) null,citoyenMobile VARCHAR(75) null,citoyenEmail VARCHAR(400) null,citoyenBirthday DATE null,hasCopyright BOOLEAN,videoUrl VARCHAR(400) null,imageTimeline LONG,opacityImage DOUBLE,isCrush BOOLEAN,crushComment TEXT null,publikId VARCHAR(75) null,imageId LONG,filesIds VARCHAR(75) null,budgetPhaseId LONG,parentId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table project_BudgetParticipatif";

	public static final String ORDER_BY_JPQL =
		" ORDER BY budgetParticipatif.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY project_BudgetParticipatif.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"value.object.entity.cache.enabled.eu.strasbourg.service.project.model.BudgetParticipatif"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"value.object.finder.cache.enabled.eu.strasbourg.service.project.model.BudgetParticipatif"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"value.object.column.bitmask.enabled.eu.strasbourg.service.project.model.BudgetParticipatif"),
		true);

	public static final long BUDGETPHASEID_COLUMN_BITMASK = 1L;

	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long ISCRUSH_COLUMN_BITMASK = 8L;

	public static final long PARENTID_COLUMN_BITMASK = 16L;

	public static final long PUBLIKID_COLUMN_BITMASK = 32L;

	public static final long STATUS_COLUMN_BITMASK = 64L;

	public static final long UUID_COLUMN_BITMASK = 128L;

	public static final long MODIFIEDDATE_COLUMN_BITMASK = 256L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static BudgetParticipatif toModel(BudgetParticipatifSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BudgetParticipatif model = new BudgetParticipatifImpl();

		model.setUuid(soapModel.getUuid());
		model.setBudgetParticipatifId(soapModel.getBudgetParticipatifId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setTitle(soapModel.getTitle());
		model.setDescription(soapModel.getDescription());
		model.setSummary(soapModel.getSummary());
		model.setBudget(soapModel.getBudget());
		model.setMotif(soapModel.getMotif());
		model.setPlaceTextArea(soapModel.getPlaceTextArea());
		model.setInTheNameOf(soapModel.getInTheNameOf());
		model.setCitoyenLastname(soapModel.getCitoyenLastname());
		model.setCitoyenFirstname(soapModel.getCitoyenFirstname());
		model.setCitoyenAdresse(soapModel.getCitoyenAdresse());
		model.setCitoyenPostalCode(soapModel.getCitoyenPostalCode());
		model.setCitoyenCity(soapModel.getCitoyenCity());
		model.setCitoyenPhone(soapModel.getCitoyenPhone());
		model.setCitoyenMobile(soapModel.getCitoyenMobile());
		model.setCitoyenEmail(soapModel.getCitoyenEmail());
		model.setCitoyenBirthday(soapModel.getCitoyenBirthday());
		model.setHasCopyright(soapModel.isHasCopyright());
		model.setVideoUrl(soapModel.getVideoUrl());
		model.setImageTimeline(soapModel.getImageTimeline());
		model.setOpacityImage(soapModel.getOpacityImage());
		model.setIsCrush(soapModel.isIsCrush());
		model.setCrushComment(soapModel.getCrushComment());
		model.setPublikId(soapModel.getPublikId());
		model.setImageId(soapModel.getImageId());
		model.setFilesIds(soapModel.getFilesIds());
		model.setBudgetPhaseId(soapModel.getBudgetPhaseId());
		model.setParentId(soapModel.getParentId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<BudgetParticipatif> toModels(
		BudgetParticipatifSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<BudgetParticipatif> models = new ArrayList<BudgetParticipatif>(
			soapModels.length);

		for (BudgetParticipatifSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.project.model.BudgetParticipatif"));

	public BudgetParticipatifModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _budgetParticipatifId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBudgetParticipatifId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _budgetParticipatifId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BudgetParticipatif.class;
	}

	@Override
	public String getModelClassName() {
		return BudgetParticipatif.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BudgetParticipatif, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BudgetParticipatif, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BudgetParticipatif, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BudgetParticipatif)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BudgetParticipatif, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BudgetParticipatif, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BudgetParticipatif)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BudgetParticipatif, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BudgetParticipatif, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, BudgetParticipatif>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			BudgetParticipatif.class.getClassLoader(), BudgetParticipatif.class,
			ModelWrapper.class);

		try {
			Constructor<BudgetParticipatif> constructor =
				(Constructor<BudgetParticipatif>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<BudgetParticipatif, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<BudgetParticipatif, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<BudgetParticipatif, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<BudgetParticipatif, Object>>();
		Map<String, BiConsumer<BudgetParticipatif, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<BudgetParticipatif, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object uuid) {

					budgetParticipatif.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"budgetParticipatifId",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getBudgetParticipatifId();
				}

			});
		attributeSetterBiConsumers.put(
			"budgetParticipatifId",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object budgetParticipatifId) {

					budgetParticipatif.setBudgetParticipatifId(
						(Long)budgetParticipatifId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object groupId) {

					budgetParticipatif.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object companyId) {

					budgetParticipatif.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object userId) {

					budgetParticipatif.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object userName) {

					budgetParticipatif.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object createDate) {

					budgetParticipatif.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object modifiedDate) {

					budgetParticipatif.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object status) {

					budgetParticipatif.setStatus((Integer)status);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserId",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getStatusByUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserId",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object statusByUserId) {

					budgetParticipatif.setStatusByUserId((Long)statusByUserId);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserName",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getStatusByUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserName",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object statusByUserName) {

					budgetParticipatif.setStatusByUserName(
						(String)statusByUserName);
				}

			});
		attributeGetterFunctions.put(
			"statusDate",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getStatusDate();
				}

			});
		attributeSetterBiConsumers.put(
			"statusDate",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object statusDate) {

					budgetParticipatif.setStatusDate((Date)statusDate);
				}

			});
		attributeGetterFunctions.put(
			"title",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getTitle();
				}

			});
		attributeSetterBiConsumers.put(
			"title",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object title) {

					budgetParticipatif.setTitle((String)title);
				}

			});
		attributeGetterFunctions.put(
			"description",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getDescription();
				}

			});
		attributeSetterBiConsumers.put(
			"description",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object description) {

					budgetParticipatif.setDescription((String)description);
				}

			});
		attributeGetterFunctions.put(
			"summary",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getSummary();
				}

			});
		attributeSetterBiConsumers.put(
			"summary",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object summary) {

					budgetParticipatif.setSummary((String)summary);
				}

			});
		attributeGetterFunctions.put(
			"budget",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getBudget();
				}

			});
		attributeSetterBiConsumers.put(
			"budget",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object budget) {

					budgetParticipatif.setBudget((String)budget);
				}

			});
		attributeGetterFunctions.put(
			"motif",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getMotif();
				}

			});
		attributeSetterBiConsumers.put(
			"motif",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object motif) {

					budgetParticipatif.setMotif((String)motif);
				}

			});
		attributeGetterFunctions.put(
			"placeTextArea",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getPlaceTextArea();
				}

			});
		attributeSetterBiConsumers.put(
			"placeTextArea",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object placeTextArea) {

					budgetParticipatif.setPlaceTextArea((String)placeTextArea);
				}

			});
		attributeGetterFunctions.put(
			"inTheNameOf",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getInTheNameOf();
				}

			});
		attributeSetterBiConsumers.put(
			"inTheNameOf",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object inTheNameOf) {

					budgetParticipatif.setInTheNameOf((String)inTheNameOf);
				}

			});
		attributeGetterFunctions.put(
			"citoyenLastname",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getCitoyenLastname();
				}

			});
		attributeSetterBiConsumers.put(
			"citoyenLastname",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object citoyenLastname) {

					budgetParticipatif.setCitoyenLastname(
						(String)citoyenLastname);
				}

			});
		attributeGetterFunctions.put(
			"citoyenFirstname",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getCitoyenFirstname();
				}

			});
		attributeSetterBiConsumers.put(
			"citoyenFirstname",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object citoyenFirstname) {

					budgetParticipatif.setCitoyenFirstname(
						(String)citoyenFirstname);
				}

			});
		attributeGetterFunctions.put(
			"citoyenAdresse",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getCitoyenAdresse();
				}

			});
		attributeSetterBiConsumers.put(
			"citoyenAdresse",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object citoyenAdresse) {

					budgetParticipatif.setCitoyenAdresse(
						(String)citoyenAdresse);
				}

			});
		attributeGetterFunctions.put(
			"citoyenPostalCode",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getCitoyenPostalCode();
				}

			});
		attributeSetterBiConsumers.put(
			"citoyenPostalCode",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object citoyenPostalCode) {

					budgetParticipatif.setCitoyenPostalCode(
						(Long)citoyenPostalCode);
				}

			});
		attributeGetterFunctions.put(
			"citoyenCity",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getCitoyenCity();
				}

			});
		attributeSetterBiConsumers.put(
			"citoyenCity",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object citoyenCity) {

					budgetParticipatif.setCitoyenCity((String)citoyenCity);
				}

			});
		attributeGetterFunctions.put(
			"citoyenPhone",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getCitoyenPhone();
				}

			});
		attributeSetterBiConsumers.put(
			"citoyenPhone",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object citoyenPhone) {

					budgetParticipatif.setCitoyenPhone((String)citoyenPhone);
				}

			});
		attributeGetterFunctions.put(
			"citoyenMobile",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getCitoyenMobile();
				}

			});
		attributeSetterBiConsumers.put(
			"citoyenMobile",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object citoyenMobile) {

					budgetParticipatif.setCitoyenMobile((String)citoyenMobile);
				}

			});
		attributeGetterFunctions.put(
			"citoyenEmail",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getCitoyenEmail();
				}

			});
		attributeSetterBiConsumers.put(
			"citoyenEmail",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object citoyenEmail) {

					budgetParticipatif.setCitoyenEmail((String)citoyenEmail);
				}

			});
		attributeGetterFunctions.put(
			"citoyenBirthday",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getCitoyenBirthday();
				}

			});
		attributeSetterBiConsumers.put(
			"citoyenBirthday",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object citoyenBirthday) {

					budgetParticipatif.setCitoyenBirthday(
						(Date)citoyenBirthday);
				}

			});
		attributeGetterFunctions.put(
			"hasCopyright",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getHasCopyright();
				}

			});
		attributeSetterBiConsumers.put(
			"hasCopyright",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object hasCopyright) {

					budgetParticipatif.setHasCopyright((Boolean)hasCopyright);
				}

			});
		attributeGetterFunctions.put(
			"videoUrl",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getVideoUrl();
				}

			});
		attributeSetterBiConsumers.put(
			"videoUrl",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object videoUrl) {

					budgetParticipatif.setVideoUrl((String)videoUrl);
				}

			});
		attributeGetterFunctions.put(
			"imageTimeline",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getImageTimeline();
				}

			});
		attributeSetterBiConsumers.put(
			"imageTimeline",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object imageTimeline) {

					budgetParticipatif.setImageTimeline((Long)imageTimeline);
				}

			});
		attributeGetterFunctions.put(
			"opacityImage",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getOpacityImage();
				}

			});
		attributeSetterBiConsumers.put(
			"opacityImage",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object opacityImage) {

					budgetParticipatif.setOpacityImage((Double)opacityImage);
				}

			});
		attributeGetterFunctions.put(
			"isCrush",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getIsCrush();
				}

			});
		attributeSetterBiConsumers.put(
			"isCrush",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object isCrush) {

					budgetParticipatif.setIsCrush((Boolean)isCrush);
				}

			});
		attributeGetterFunctions.put(
			"crushComment",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getCrushComment();
				}

			});
		attributeSetterBiConsumers.put(
			"crushComment",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object crushComment) {

					budgetParticipatif.setCrushComment((String)crushComment);
				}

			});
		attributeGetterFunctions.put(
			"publikId",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getPublikId();
				}

			});
		attributeSetterBiConsumers.put(
			"publikId",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object publikId) {

					budgetParticipatif.setPublikId((String)publikId);
				}

			});
		attributeGetterFunctions.put(
			"imageId",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getImageId();
				}

			});
		attributeSetterBiConsumers.put(
			"imageId",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object imageId) {

					budgetParticipatif.setImageId((Long)imageId);
				}

			});
		attributeGetterFunctions.put(
			"filesIds",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getFilesIds();
				}

			});
		attributeSetterBiConsumers.put(
			"filesIds",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object filesIds) {

					budgetParticipatif.setFilesIds((String)filesIds);
				}

			});
		attributeGetterFunctions.put(
			"budgetPhaseId",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getBudgetPhaseId();
				}

			});
		attributeSetterBiConsumers.put(
			"budgetPhaseId",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif,
					Object budgetPhaseId) {

					budgetParticipatif.setBudgetPhaseId((Long)budgetPhaseId);
				}

			});
		attributeGetterFunctions.put(
			"parentId",
			new Function<BudgetParticipatif, Object>() {

				@Override
				public Object apply(BudgetParticipatif budgetParticipatif) {
					return budgetParticipatif.getParentId();
				}

			});
		attributeSetterBiConsumers.put(
			"parentId",
			new BiConsumer<BudgetParticipatif, Object>() {

				@Override
				public void accept(
					BudgetParticipatif budgetParticipatif, Object parentId) {

					budgetParticipatif.setParentId((Long)parentId);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getBudgetParticipatifId() {
		return _budgetParticipatifId;
	}

	@Override
	public void setBudgetParticipatifId(long budgetParticipatifId) {
		_budgetParticipatifId = budgetParticipatifId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public String getSummary() {
		if (_summary == null) {
			return "";
		}
		else {
			return _summary;
		}
	}

	@Override
	public void setSummary(String summary) {
		_summary = summary;
	}

	@JSON
	@Override
	public String getBudget() {
		if (_budget == null) {
			return "";
		}
		else {
			return _budget;
		}
	}

	@Override
	public void setBudget(String budget) {
		_budget = budget;
	}

	@JSON
	@Override
	public String getMotif() {
		if (_motif == null) {
			return "";
		}
		else {
			return _motif;
		}
	}

	@Override
	public void setMotif(String motif) {
		_motif = motif;
	}

	@JSON
	@Override
	public String getPlaceTextArea() {
		if (_placeTextArea == null) {
			return "";
		}
		else {
			return _placeTextArea;
		}
	}

	@Override
	public void setPlaceTextArea(String placeTextArea) {
		_placeTextArea = placeTextArea;
	}

	@JSON
	@Override
	public String getInTheNameOf() {
		if (_inTheNameOf == null) {
			return "";
		}
		else {
			return _inTheNameOf;
		}
	}

	@Override
	public void setInTheNameOf(String inTheNameOf) {
		_inTheNameOf = inTheNameOf;
	}

	@JSON
	@Override
	public String getCitoyenLastname() {
		if (_citoyenLastname == null) {
			return "";
		}
		else {
			return _citoyenLastname;
		}
	}

	@Override
	public void setCitoyenLastname(String citoyenLastname) {
		_citoyenLastname = citoyenLastname;
	}

	@JSON
	@Override
	public String getCitoyenFirstname() {
		if (_citoyenFirstname == null) {
			return "";
		}
		else {
			return _citoyenFirstname;
		}
	}

	@Override
	public void setCitoyenFirstname(String citoyenFirstname) {
		_citoyenFirstname = citoyenFirstname;
	}

	@JSON
	@Override
	public String getCitoyenAdresse() {
		if (_citoyenAdresse == null) {
			return "";
		}
		else {
			return _citoyenAdresse;
		}
	}

	@Override
	public void setCitoyenAdresse(String citoyenAdresse) {
		_citoyenAdresse = citoyenAdresse;
	}

	@JSON
	@Override
	public long getCitoyenPostalCode() {
		return _citoyenPostalCode;
	}

	@Override
	public void setCitoyenPostalCode(long citoyenPostalCode) {
		_citoyenPostalCode = citoyenPostalCode;
	}

	@JSON
	@Override
	public String getCitoyenCity() {
		if (_citoyenCity == null) {
			return "";
		}
		else {
			return _citoyenCity;
		}
	}

	@Override
	public void setCitoyenCity(String citoyenCity) {
		_citoyenCity = citoyenCity;
	}

	@JSON
	@Override
	public String getCitoyenPhone() {
		if (_citoyenPhone == null) {
			return "";
		}
		else {
			return _citoyenPhone;
		}
	}

	@Override
	public void setCitoyenPhone(String citoyenPhone) {
		_citoyenPhone = citoyenPhone;
	}

	@JSON
	@Override
	public String getCitoyenMobile() {
		if (_citoyenMobile == null) {
			return "";
		}
		else {
			return _citoyenMobile;
		}
	}

	@Override
	public void setCitoyenMobile(String citoyenMobile) {
		_citoyenMobile = citoyenMobile;
	}

	@JSON
	@Override
	public String getCitoyenEmail() {
		if (_citoyenEmail == null) {
			return "";
		}
		else {
			return _citoyenEmail;
		}
	}

	@Override
	public void setCitoyenEmail(String citoyenEmail) {
		_citoyenEmail = citoyenEmail;
	}

	@JSON
	@Override
	public Date getCitoyenBirthday() {
		return _citoyenBirthday;
	}

	@Override
	public void setCitoyenBirthday(Date citoyenBirthday) {
		_citoyenBirthday = citoyenBirthday;
	}

	@JSON
	@Override
	public boolean getHasCopyright() {
		return _hasCopyright;
	}

	@JSON
	@Override
	public boolean isHasCopyright() {
		return _hasCopyright;
	}

	@Override
	public void setHasCopyright(boolean hasCopyright) {
		_hasCopyright = hasCopyright;
	}

	@JSON
	@Override
	public String getVideoUrl() {
		if (_videoUrl == null) {
			return "";
		}
		else {
			return _videoUrl;
		}
	}

	@Override
	public void setVideoUrl(String videoUrl) {
		_videoUrl = videoUrl;
	}

	@JSON
	@Override
	public long getImageTimeline() {
		return _imageTimeline;
	}

	@Override
	public void setImageTimeline(long imageTimeline) {
		_imageTimeline = imageTimeline;
	}

	@JSON
	@Override
	public double getOpacityImage() {
		return _opacityImage;
	}

	@Override
	public void setOpacityImage(double opacityImage) {
		_opacityImage = opacityImage;
	}

	@JSON
	@Override
	public boolean getIsCrush() {
		return _isCrush;
	}

	@JSON
	@Override
	public boolean isIsCrush() {
		return _isCrush;
	}

	@Override
	public void setIsCrush(boolean isCrush) {
		_columnBitmask |= ISCRUSH_COLUMN_BITMASK;

		if (!_setOriginalIsCrush) {
			_setOriginalIsCrush = true;

			_originalIsCrush = _isCrush;
		}

		_isCrush = isCrush;
	}

	public boolean getOriginalIsCrush() {
		return _originalIsCrush;
	}

	@JSON
	@Override
	public String getCrushComment() {
		if (_crushComment == null) {
			return "";
		}
		else {
			return _crushComment;
		}
	}

	@Override
	public void setCrushComment(String crushComment) {
		_crushComment = crushComment;
	}

	@JSON
	@Override
	public String getPublikId() {
		if (_publikId == null) {
			return "";
		}
		else {
			return _publikId;
		}
	}

	@Override
	public void setPublikId(String publikId) {
		_columnBitmask |= PUBLIKID_COLUMN_BITMASK;

		if (_originalPublikId == null) {
			_originalPublikId = _publikId;
		}

		_publikId = publikId;
	}

	public String getOriginalPublikId() {
		return GetterUtil.getString(_originalPublikId);
	}

	@JSON
	@Override
	public long getImageId() {
		return _imageId;
	}

	@Override
	public void setImageId(long imageId) {
		_imageId = imageId;
	}

	@JSON
	@Override
	public String getFilesIds() {
		if (_filesIds == null) {
			return "";
		}
		else {
			return _filesIds;
		}
	}

	@Override
	public void setFilesIds(String filesIds) {
		_filesIds = filesIds;
	}

	@JSON
	@Override
	public long getBudgetPhaseId() {
		return _budgetPhaseId;
	}

	@Override
	public void setBudgetPhaseId(long budgetPhaseId) {
		_columnBitmask |= BUDGETPHASEID_COLUMN_BITMASK;

		if (!_setOriginalBudgetPhaseId) {
			_setOriginalBudgetPhaseId = true;

			_originalBudgetPhaseId = _budgetPhaseId;
		}

		_budgetPhaseId = budgetPhaseId;
	}

	public long getOriginalBudgetPhaseId() {
		return _originalBudgetPhaseId;
	}

	@JSON
	@Override
	public long getParentId() {
		return _parentId;
	}

	@Override
	public void setParentId(long parentId) {
		_columnBitmask |= PARENTID_COLUMN_BITMASK;

		if (!_setOriginalParentId) {
			_setOriginalParentId = true;

			_originalParentId = _parentId;
		}

		_parentId = parentId;
	}

	public long getOriginalParentId() {
		return _originalParentId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(BudgetParticipatif.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), BudgetParticipatif.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BudgetParticipatif toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BudgetParticipatifImpl budgetParticipatifImpl =
			new BudgetParticipatifImpl();

		budgetParticipatifImpl.setUuid(getUuid());
		budgetParticipatifImpl.setBudgetParticipatifId(
			getBudgetParticipatifId());
		budgetParticipatifImpl.setGroupId(getGroupId());
		budgetParticipatifImpl.setCompanyId(getCompanyId());
		budgetParticipatifImpl.setUserId(getUserId());
		budgetParticipatifImpl.setUserName(getUserName());
		budgetParticipatifImpl.setCreateDate(getCreateDate());
		budgetParticipatifImpl.setModifiedDate(getModifiedDate());
		budgetParticipatifImpl.setStatus(getStatus());
		budgetParticipatifImpl.setStatusByUserId(getStatusByUserId());
		budgetParticipatifImpl.setStatusByUserName(getStatusByUserName());
		budgetParticipatifImpl.setStatusDate(getStatusDate());
		budgetParticipatifImpl.setTitle(getTitle());
		budgetParticipatifImpl.setDescription(getDescription());
		budgetParticipatifImpl.setSummary(getSummary());
		budgetParticipatifImpl.setBudget(getBudget());
		budgetParticipatifImpl.setMotif(getMotif());
		budgetParticipatifImpl.setPlaceTextArea(getPlaceTextArea());
		budgetParticipatifImpl.setInTheNameOf(getInTheNameOf());
		budgetParticipatifImpl.setCitoyenLastname(getCitoyenLastname());
		budgetParticipatifImpl.setCitoyenFirstname(getCitoyenFirstname());
		budgetParticipatifImpl.setCitoyenAdresse(getCitoyenAdresse());
		budgetParticipatifImpl.setCitoyenPostalCode(getCitoyenPostalCode());
		budgetParticipatifImpl.setCitoyenCity(getCitoyenCity());
		budgetParticipatifImpl.setCitoyenPhone(getCitoyenPhone());
		budgetParticipatifImpl.setCitoyenMobile(getCitoyenMobile());
		budgetParticipatifImpl.setCitoyenEmail(getCitoyenEmail());
		budgetParticipatifImpl.setCitoyenBirthday(getCitoyenBirthday());
		budgetParticipatifImpl.setHasCopyright(isHasCopyright());
		budgetParticipatifImpl.setVideoUrl(getVideoUrl());
		budgetParticipatifImpl.setImageTimeline(getImageTimeline());
		budgetParticipatifImpl.setOpacityImage(getOpacityImage());
		budgetParticipatifImpl.setIsCrush(isIsCrush());
		budgetParticipatifImpl.setCrushComment(getCrushComment());
		budgetParticipatifImpl.setPublikId(getPublikId());
		budgetParticipatifImpl.setImageId(getImageId());
		budgetParticipatifImpl.setFilesIds(getFilesIds());
		budgetParticipatifImpl.setBudgetPhaseId(getBudgetPhaseId());
		budgetParticipatifImpl.setParentId(getParentId());

		budgetParticipatifImpl.resetOriginalValues();

		return budgetParticipatifImpl;
	}

	@Override
	public int compareTo(BudgetParticipatif budgetParticipatif) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), budgetParticipatif.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BudgetParticipatif)) {
			return false;
		}

		BudgetParticipatif budgetParticipatif = (BudgetParticipatif)obj;

		long primaryKey = budgetParticipatif.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		BudgetParticipatifModelImpl budgetParticipatifModelImpl = this;

		budgetParticipatifModelImpl._originalUuid =
			budgetParticipatifModelImpl._uuid;

		budgetParticipatifModelImpl._originalGroupId =
			budgetParticipatifModelImpl._groupId;

		budgetParticipatifModelImpl._setOriginalGroupId = false;

		budgetParticipatifModelImpl._originalCompanyId =
			budgetParticipatifModelImpl._companyId;

		budgetParticipatifModelImpl._setOriginalCompanyId = false;

		budgetParticipatifModelImpl._setModifiedDate = false;

		budgetParticipatifModelImpl._originalStatus =
			budgetParticipatifModelImpl._status;

		budgetParticipatifModelImpl._setOriginalStatus = false;

		budgetParticipatifModelImpl._originalIsCrush =
			budgetParticipatifModelImpl._isCrush;

		budgetParticipatifModelImpl._setOriginalIsCrush = false;

		budgetParticipatifModelImpl._originalPublikId =
			budgetParticipatifModelImpl._publikId;

		budgetParticipatifModelImpl._originalBudgetPhaseId =
			budgetParticipatifModelImpl._budgetPhaseId;

		budgetParticipatifModelImpl._setOriginalBudgetPhaseId = false;

		budgetParticipatifModelImpl._originalParentId =
			budgetParticipatifModelImpl._parentId;

		budgetParticipatifModelImpl._setOriginalParentId = false;

		budgetParticipatifModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BudgetParticipatif> toCacheModel() {
		BudgetParticipatifCacheModel budgetParticipatifCacheModel =
			new BudgetParticipatifCacheModel();

		budgetParticipatifCacheModel.uuid = getUuid();

		String uuid = budgetParticipatifCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			budgetParticipatifCacheModel.uuid = null;
		}

		budgetParticipatifCacheModel.budgetParticipatifId =
			getBudgetParticipatifId();

		budgetParticipatifCacheModel.groupId = getGroupId();

		budgetParticipatifCacheModel.companyId = getCompanyId();

		budgetParticipatifCacheModel.userId = getUserId();

		budgetParticipatifCacheModel.userName = getUserName();

		String userName = budgetParticipatifCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			budgetParticipatifCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			budgetParticipatifCacheModel.createDate = createDate.getTime();
		}
		else {
			budgetParticipatifCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			budgetParticipatifCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			budgetParticipatifCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		budgetParticipatifCacheModel.status = getStatus();

		budgetParticipatifCacheModel.statusByUserId = getStatusByUserId();

		budgetParticipatifCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = budgetParticipatifCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			budgetParticipatifCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			budgetParticipatifCacheModel.statusDate = statusDate.getTime();
		}
		else {
			budgetParticipatifCacheModel.statusDate = Long.MIN_VALUE;
		}

		budgetParticipatifCacheModel.title = getTitle();

		String title = budgetParticipatifCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			budgetParticipatifCacheModel.title = null;
		}

		budgetParticipatifCacheModel.description = getDescription();

		String description = budgetParticipatifCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			budgetParticipatifCacheModel.description = null;
		}

		budgetParticipatifCacheModel.summary = getSummary();

		String summary = budgetParticipatifCacheModel.summary;

		if ((summary != null) && (summary.length() == 0)) {
			budgetParticipatifCacheModel.summary = null;
		}

		budgetParticipatifCacheModel.budget = getBudget();

		String budget = budgetParticipatifCacheModel.budget;

		if ((budget != null) && (budget.length() == 0)) {
			budgetParticipatifCacheModel.budget = null;
		}

		budgetParticipatifCacheModel.motif = getMotif();

		String motif = budgetParticipatifCacheModel.motif;

		if ((motif != null) && (motif.length() == 0)) {
			budgetParticipatifCacheModel.motif = null;
		}

		budgetParticipatifCacheModel.placeTextArea = getPlaceTextArea();

		String placeTextArea = budgetParticipatifCacheModel.placeTextArea;

		if ((placeTextArea != null) && (placeTextArea.length() == 0)) {
			budgetParticipatifCacheModel.placeTextArea = null;
		}

		budgetParticipatifCacheModel.inTheNameOf = getInTheNameOf();

		String inTheNameOf = budgetParticipatifCacheModel.inTheNameOf;

		if ((inTheNameOf != null) && (inTheNameOf.length() == 0)) {
			budgetParticipatifCacheModel.inTheNameOf = null;
		}

		budgetParticipatifCacheModel.citoyenLastname = getCitoyenLastname();

		String citoyenLastname = budgetParticipatifCacheModel.citoyenLastname;

		if ((citoyenLastname != null) && (citoyenLastname.length() == 0)) {
			budgetParticipatifCacheModel.citoyenLastname = null;
		}

		budgetParticipatifCacheModel.citoyenFirstname = getCitoyenFirstname();

		String citoyenFirstname = budgetParticipatifCacheModel.citoyenFirstname;

		if ((citoyenFirstname != null) && (citoyenFirstname.length() == 0)) {
			budgetParticipatifCacheModel.citoyenFirstname = null;
		}

		budgetParticipatifCacheModel.citoyenAdresse = getCitoyenAdresse();

		String citoyenAdresse = budgetParticipatifCacheModel.citoyenAdresse;

		if ((citoyenAdresse != null) && (citoyenAdresse.length() == 0)) {
			budgetParticipatifCacheModel.citoyenAdresse = null;
		}

		budgetParticipatifCacheModel.citoyenPostalCode = getCitoyenPostalCode();

		budgetParticipatifCacheModel.citoyenCity = getCitoyenCity();

		String citoyenCity = budgetParticipatifCacheModel.citoyenCity;

		if ((citoyenCity != null) && (citoyenCity.length() == 0)) {
			budgetParticipatifCacheModel.citoyenCity = null;
		}

		budgetParticipatifCacheModel.citoyenPhone = getCitoyenPhone();

		String citoyenPhone = budgetParticipatifCacheModel.citoyenPhone;

		if ((citoyenPhone != null) && (citoyenPhone.length() == 0)) {
			budgetParticipatifCacheModel.citoyenPhone = null;
		}

		budgetParticipatifCacheModel.citoyenMobile = getCitoyenMobile();

		String citoyenMobile = budgetParticipatifCacheModel.citoyenMobile;

		if ((citoyenMobile != null) && (citoyenMobile.length() == 0)) {
			budgetParticipatifCacheModel.citoyenMobile = null;
		}

		budgetParticipatifCacheModel.citoyenEmail = getCitoyenEmail();

		String citoyenEmail = budgetParticipatifCacheModel.citoyenEmail;

		if ((citoyenEmail != null) && (citoyenEmail.length() == 0)) {
			budgetParticipatifCacheModel.citoyenEmail = null;
		}

		Date citoyenBirthday = getCitoyenBirthday();

		if (citoyenBirthday != null) {
			budgetParticipatifCacheModel.citoyenBirthday =
				citoyenBirthday.getTime();
		}
		else {
			budgetParticipatifCacheModel.citoyenBirthday = Long.MIN_VALUE;
		}

		budgetParticipatifCacheModel.hasCopyright = isHasCopyright();

		budgetParticipatifCacheModel.videoUrl = getVideoUrl();

		String videoUrl = budgetParticipatifCacheModel.videoUrl;

		if ((videoUrl != null) && (videoUrl.length() == 0)) {
			budgetParticipatifCacheModel.videoUrl = null;
		}

		budgetParticipatifCacheModel.imageTimeline = getImageTimeline();

		budgetParticipatifCacheModel.opacityImage = getOpacityImage();

		budgetParticipatifCacheModel.isCrush = isIsCrush();

		budgetParticipatifCacheModel.crushComment = getCrushComment();

		String crushComment = budgetParticipatifCacheModel.crushComment;

		if ((crushComment != null) && (crushComment.length() == 0)) {
			budgetParticipatifCacheModel.crushComment = null;
		}

		budgetParticipatifCacheModel.publikId = getPublikId();

		String publikId = budgetParticipatifCacheModel.publikId;

		if ((publikId != null) && (publikId.length() == 0)) {
			budgetParticipatifCacheModel.publikId = null;
		}

		budgetParticipatifCacheModel.imageId = getImageId();

		budgetParticipatifCacheModel.filesIds = getFilesIds();

		String filesIds = budgetParticipatifCacheModel.filesIds;

		if ((filesIds != null) && (filesIds.length() == 0)) {
			budgetParticipatifCacheModel.filesIds = null;
		}

		budgetParticipatifCacheModel.budgetPhaseId = getBudgetPhaseId();

		budgetParticipatifCacheModel.parentId = getParentId();

		return budgetParticipatifCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BudgetParticipatif, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BudgetParticipatif, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BudgetParticipatif, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((BudgetParticipatif)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<BudgetParticipatif, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<BudgetParticipatif, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BudgetParticipatif, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((BudgetParticipatif)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, BudgetParticipatif>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private String _uuid;
	private String _originalUuid;
	private long _budgetParticipatifId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _title;
	private String _description;
	private String _summary;
	private String _budget;
	private String _motif;
	private String _placeTextArea;
	private String _inTheNameOf;
	private String _citoyenLastname;
	private String _citoyenFirstname;
	private String _citoyenAdresse;
	private long _citoyenPostalCode;
	private String _citoyenCity;
	private String _citoyenPhone;
	private String _citoyenMobile;
	private String _citoyenEmail;
	private Date _citoyenBirthday;
	private boolean _hasCopyright;
	private String _videoUrl;
	private long _imageTimeline;
	private double _opacityImage;
	private boolean _isCrush;
	private boolean _originalIsCrush;
	private boolean _setOriginalIsCrush;
	private String _crushComment;
	private String _publikId;
	private String _originalPublikId;
	private long _imageId;
	private String _filesIds;
	private long _budgetPhaseId;
	private long _originalBudgetPhaseId;
	private boolean _setOriginalBudgetPhaseId;
	private long _parentId;
	private long _originalParentId;
	private boolean _setOriginalParentId;
	private long _columnBitmask;
	private BudgetParticipatif _escapedModel;

}