/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.project.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.project.model.Project;
import eu.strasbourg.service.project.model.ProjectModel;
import eu.strasbourg.service.project.model.ProjectSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Project service. Represents a row in the &quot;project_Project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProjectModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProjectImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see ProjectImpl
 * @generated
 */
@JSON(strict = true)
public class ProjectModelImpl
	extends BaseModelImpl<Project> implements ProjectModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a project model instance should use the <code>Project</code> interface instead.
	 */
	public static final String TABLE_NAME = "project_Project";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"projectId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"title", Types.VARCHAR}, {"externalImageURL", Types.VARCHAR},
		{"externalImageCopyright", Types.VARCHAR},
		{"opacityImage", Types.DOUBLE}, {"description", Types.CLOB},
		{"detailURL", Types.VARCHAR}, {"budget", Types.VARCHAR},
		{"label", Types.VARCHAR}, {"duration", Types.VARCHAR},
		{"partners", Types.CLOB}, {"contactName", Types.VARCHAR},
		{"contactLine1", Types.VARCHAR}, {"contactLine2", Types.VARCHAR},
		{"contactPhoneNumber", Types.VARCHAR}, {"imageId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalImageURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("externalImageCopyright", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("opacityImage", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("description", Types.CLOB);
		TABLE_COLUMNS_MAP.put("detailURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("budget", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("label", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("duration", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("partners", Types.CLOB);
		TABLE_COLUMNS_MAP.put("contactName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactLine1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactLine2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactPhoneNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("imageId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table project_Project (uuid_ VARCHAR(75) null,projectId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,title VARCHAR(400) null,externalImageURL VARCHAR(400) null,externalImageCopyright VARCHAR(400) null,opacityImage DOUBLE,description TEXT null,detailURL VARCHAR(75) null,budget VARCHAR(75) null,label VARCHAR(75) null,duration VARCHAR(75) null,partners TEXT null,contactName VARCHAR(75) null,contactLine1 VARCHAR(400) null,contactLine2 VARCHAR(400) null,contactPhoneNumber VARCHAR(75) null,imageId LONG)";

	public static final String TABLE_SQL_DROP = "drop table project_Project";

	public static final String ORDER_BY_JPQL = " ORDER BY project.title ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY project_Project.title ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"value.object.entity.cache.enabled.eu.strasbourg.service.project.model.Project"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"value.object.finder.cache.enabled.eu.strasbourg.service.project.model.Project"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"value.object.column.bitmask.enabled.eu.strasbourg.service.project.model.Project"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long STATUS_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long TITLE_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Project toModel(ProjectSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Project model = new ProjectImpl();

		model.setUuid(soapModel.getUuid());
		model.setProjectId(soapModel.getProjectId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setTitle(soapModel.getTitle());
		model.setExternalImageURL(soapModel.getExternalImageURL());
		model.setExternalImageCopyright(soapModel.getExternalImageCopyright());
		model.setOpacityImage(soapModel.getOpacityImage());
		model.setDescription(soapModel.getDescription());
		model.setDetailURL(soapModel.getDetailURL());
		model.setBudget(soapModel.getBudget());
		model.setLabel(soapModel.getLabel());
		model.setDuration(soapModel.getDuration());
		model.setPartners(soapModel.getPartners());
		model.setContactName(soapModel.getContactName());
		model.setContactLine1(soapModel.getContactLine1());
		model.setContactLine2(soapModel.getContactLine2());
		model.setContactPhoneNumber(soapModel.getContactPhoneNumber());
		model.setImageId(soapModel.getImageId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Project> toModels(ProjectSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Project> models = new ArrayList<Project>(soapModels.length);

		for (ProjectSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.project.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.project.model.Project"));

	public ProjectModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _projectId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setProjectId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _projectId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Project.class;
	}

	@Override
	public String getModelClassName() {
		return Project.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Project, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Project, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Project, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Project)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Project, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Project, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Project)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Project, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Project, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Project>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Project.class.getClassLoader(), Project.class, ModelWrapper.class);

		try {
			Constructor<Project> constructor =
				(Constructor<Project>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Project, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Project, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Project, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Project, Object>>();
		Map<String, BiConsumer<Project, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Project, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object uuidObject) {
					project.setUuid((String)uuidObject);
				}

			});
		attributeGetterFunctions.put(
			"projectId",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getProjectId();
				}

			});
		attributeSetterBiConsumers.put(
			"projectId",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object projectIdObject) {
					project.setProjectId((Long)projectIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object groupIdObject) {
					project.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object companyIdObject) {
					project.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object userIdObject) {
					project.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object userNameObject) {
					project.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object createDateObject) {
					project.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object modifiedDateObject) {
					project.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object statusObject) {
					project.setStatus((Integer)statusObject);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserId",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getStatusByUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserId",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(
					Project project, Object statusByUserIdObject) {

					project.setStatusByUserId((Long)statusByUserIdObject);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserName",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getStatusByUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserName",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(
					Project project, Object statusByUserNameObject) {

					project.setStatusByUserName((String)statusByUserNameObject);
				}

			});
		attributeGetterFunctions.put(
			"statusDate",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getStatusDate();
				}

			});
		attributeSetterBiConsumers.put(
			"statusDate",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object statusDateObject) {
					project.setStatusDate((Date)statusDateObject);
				}

			});
		attributeGetterFunctions.put(
			"title",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getTitle();
				}

			});
		attributeSetterBiConsumers.put(
			"title",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object titleObject) {
					project.setTitle((String)titleObject);
				}

			});
		attributeGetterFunctions.put(
			"externalImageURL",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getExternalImageURL();
				}

			});
		attributeSetterBiConsumers.put(
			"externalImageURL",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(
					Project project, Object externalImageURLObject) {

					project.setExternalImageURL((String)externalImageURLObject);
				}

			});
		attributeGetterFunctions.put(
			"externalImageCopyright",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getExternalImageCopyright();
				}

			});
		attributeSetterBiConsumers.put(
			"externalImageCopyright",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(
					Project project, Object externalImageCopyrightObject) {

					project.setExternalImageCopyright(
						(String)externalImageCopyrightObject);
				}

			});
		attributeGetterFunctions.put(
			"opacityImage",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getOpacityImage();
				}

			});
		attributeSetterBiConsumers.put(
			"opacityImage",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object opacityImageObject) {
					project.setOpacityImage((Double)opacityImageObject);
				}

			});
		attributeGetterFunctions.put(
			"description",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getDescription();
				}

			});
		attributeSetterBiConsumers.put(
			"description",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object descriptionObject) {
					project.setDescription((String)descriptionObject);
				}

			});
		attributeGetterFunctions.put(
			"detailURL",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getDetailURL();
				}

			});
		attributeSetterBiConsumers.put(
			"detailURL",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object detailURLObject) {
					project.setDetailURL((String)detailURLObject);
				}

			});
		attributeGetterFunctions.put(
			"budget",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getBudget();
				}

			});
		attributeSetterBiConsumers.put(
			"budget",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object budgetObject) {
					project.setBudget((String)budgetObject);
				}

			});
		attributeGetterFunctions.put(
			"label",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getLabel();
				}

			});
		attributeSetterBiConsumers.put(
			"label",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object labelObject) {
					project.setLabel((String)labelObject);
				}

			});
		attributeGetterFunctions.put(
			"duration",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getDuration();
				}

			});
		attributeSetterBiConsumers.put(
			"duration",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object durationObject) {
					project.setDuration((String)durationObject);
				}

			});
		attributeGetterFunctions.put(
			"partners",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getPartners();
				}

			});
		attributeSetterBiConsumers.put(
			"partners",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object partnersObject) {
					project.setPartners((String)partnersObject);
				}

			});
		attributeGetterFunctions.put(
			"contactName",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getContactName();
				}

			});
		attributeSetterBiConsumers.put(
			"contactName",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object contactNameObject) {
					project.setContactName((String)contactNameObject);
				}

			});
		attributeGetterFunctions.put(
			"contactLine1",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getContactLine1();
				}

			});
		attributeSetterBiConsumers.put(
			"contactLine1",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object contactLine1Object) {
					project.setContactLine1((String)contactLine1Object);
				}

			});
		attributeGetterFunctions.put(
			"contactLine2",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getContactLine2();
				}

			});
		attributeSetterBiConsumers.put(
			"contactLine2",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object contactLine2Object) {
					project.setContactLine2((String)contactLine2Object);
				}

			});
		attributeGetterFunctions.put(
			"contactPhoneNumber",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getContactPhoneNumber();
				}

			});
		attributeSetterBiConsumers.put(
			"contactPhoneNumber",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(
					Project project, Object contactPhoneNumberObject) {

					project.setContactPhoneNumber(
						(String)contactPhoneNumberObject);
				}

			});
		attributeGetterFunctions.put(
			"imageId",
			new Function<Project, Object>() {

				@Override
				public Object apply(Project project) {
					return project.getImageId();
				}

			});
		attributeSetterBiConsumers.put(
			"imageId",
			new BiConsumer<Project, Object>() {

				@Override
				public void accept(Project project, Object imageIdObject) {
					project.setImageId((Long)imageIdObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_projectId = projectId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_columnBitmask = -1L;

		_title = title;
	}

	@JSON
	@Override
	public String getExternalImageURL() {
		if (_externalImageURL == null) {
			return "";
		}
		else {
			return _externalImageURL;
		}
	}

	@Override
	public void setExternalImageURL(String externalImageURL) {
		_externalImageURL = externalImageURL;
	}

	@JSON
	@Override
	public String getExternalImageCopyright() {
		if (_externalImageCopyright == null) {
			return "";
		}
		else {
			return _externalImageCopyright;
		}
	}

	@Override
	public void setExternalImageCopyright(String externalImageCopyright) {
		_externalImageCopyright = externalImageCopyright;
	}

	@JSON
	@Override
	public double getOpacityImage() {
		return _opacityImage;
	}

	@Override
	public void setOpacityImage(double opacityImage) {
		_opacityImage = opacityImage;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@JSON
	@Override
	public String getDetailURL() {
		if (_detailURL == null) {
			return "";
		}
		else {
			return _detailURL;
		}
	}

	@Override
	public void setDetailURL(String detailURL) {
		_detailURL = detailURL;
	}

	@JSON
	@Override
	public String getBudget() {
		if (_budget == null) {
			return "";
		}
		else {
			return _budget;
		}
	}

	@Override
	public void setBudget(String budget) {
		_budget = budget;
	}

	@JSON
	@Override
	public String getLabel() {
		if (_label == null) {
			return "";
		}
		else {
			return _label;
		}
	}

	@Override
	public void setLabel(String label) {
		_label = label;
	}

	@JSON
	@Override
	public String getDuration() {
		if (_duration == null) {
			return "";
		}
		else {
			return _duration;
		}
	}

	@Override
	public void setDuration(String duration) {
		_duration = duration;
	}

	@JSON
	@Override
	public String getPartners() {
		if (_partners == null) {
			return "";
		}
		else {
			return _partners;
		}
	}

	@Override
	public void setPartners(String partners) {
		_partners = partners;
	}

	@JSON
	@Override
	public String getContactName() {
		if (_contactName == null) {
			return "";
		}
		else {
			return _contactName;
		}
	}

	@Override
	public void setContactName(String contactName) {
		_contactName = contactName;
	}

	@JSON
	@Override
	public String getContactLine1() {
		if (_contactLine1 == null) {
			return "";
		}
		else {
			return _contactLine1;
		}
	}

	@Override
	public void setContactLine1(String contactLine1) {
		_contactLine1 = contactLine1;
	}

	@JSON
	@Override
	public String getContactLine2() {
		if (_contactLine2 == null) {
			return "";
		}
		else {
			return _contactLine2;
		}
	}

	@Override
	public void setContactLine2(String contactLine2) {
		_contactLine2 = contactLine2;
	}

	@JSON
	@Override
	public String getContactPhoneNumber() {
		if (_contactPhoneNumber == null) {
			return "";
		}
		else {
			return _contactPhoneNumber;
		}
	}

	@Override
	public void setContactPhoneNumber(String contactPhoneNumber) {
		_contactPhoneNumber = contactPhoneNumber;
	}

	@JSON
	@Override
	public long getImageId() {
		return _imageId;
	}

	@Override
	public void setImageId(long imageId) {
		_imageId = imageId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Project.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Project.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Project toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Project>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProjectImpl projectImpl = new ProjectImpl();

		projectImpl.setUuid(getUuid());
		projectImpl.setProjectId(getProjectId());
		projectImpl.setGroupId(getGroupId());
		projectImpl.setCompanyId(getCompanyId());
		projectImpl.setUserId(getUserId());
		projectImpl.setUserName(getUserName());
		projectImpl.setCreateDate(getCreateDate());
		projectImpl.setModifiedDate(getModifiedDate());
		projectImpl.setStatus(getStatus());
		projectImpl.setStatusByUserId(getStatusByUserId());
		projectImpl.setStatusByUserName(getStatusByUserName());
		projectImpl.setStatusDate(getStatusDate());
		projectImpl.setTitle(getTitle());
		projectImpl.setExternalImageURL(getExternalImageURL());
		projectImpl.setExternalImageCopyright(getExternalImageCopyright());
		projectImpl.setOpacityImage(getOpacityImage());
		projectImpl.setDescription(getDescription());
		projectImpl.setDetailURL(getDetailURL());
		projectImpl.setBudget(getBudget());
		projectImpl.setLabel(getLabel());
		projectImpl.setDuration(getDuration());
		projectImpl.setPartners(getPartners());
		projectImpl.setContactName(getContactName());
		projectImpl.setContactLine1(getContactLine1());
		projectImpl.setContactLine2(getContactLine2());
		projectImpl.setContactPhoneNumber(getContactPhoneNumber());
		projectImpl.setImageId(getImageId());

		projectImpl.resetOriginalValues();

		return projectImpl;
	}

	@Override
	public int compareTo(Project project) {
		int value = 0;

		value = getTitle().compareTo(project.getTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Project)) {
			return false;
		}

		Project project = (Project)object;

		long primaryKey = project.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ProjectModelImpl projectModelImpl = this;

		projectModelImpl._originalUuid = projectModelImpl._uuid;

		projectModelImpl._originalGroupId = projectModelImpl._groupId;

		projectModelImpl._setOriginalGroupId = false;

		projectModelImpl._originalCompanyId = projectModelImpl._companyId;

		projectModelImpl._setOriginalCompanyId = false;

		projectModelImpl._setModifiedDate = false;

		projectModelImpl._originalStatus = projectModelImpl._status;

		projectModelImpl._setOriginalStatus = false;

		projectModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Project> toCacheModel() {
		ProjectCacheModel projectCacheModel = new ProjectCacheModel();

		projectCacheModel.uuid = getUuid();

		String uuid = projectCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			projectCacheModel.uuid = null;
		}

		projectCacheModel.projectId = getProjectId();

		projectCacheModel.groupId = getGroupId();

		projectCacheModel.companyId = getCompanyId();

		projectCacheModel.userId = getUserId();

		projectCacheModel.userName = getUserName();

		String userName = projectCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			projectCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			projectCacheModel.createDate = createDate.getTime();
		}
		else {
			projectCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			projectCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			projectCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		projectCacheModel.status = getStatus();

		projectCacheModel.statusByUserId = getStatusByUserId();

		projectCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = projectCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			projectCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			projectCacheModel.statusDate = statusDate.getTime();
		}
		else {
			projectCacheModel.statusDate = Long.MIN_VALUE;
		}

		projectCacheModel.title = getTitle();

		String title = projectCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			projectCacheModel.title = null;
		}

		projectCacheModel.externalImageURL = getExternalImageURL();

		String externalImageURL = projectCacheModel.externalImageURL;

		if ((externalImageURL != null) && (externalImageURL.length() == 0)) {
			projectCacheModel.externalImageURL = null;
		}

		projectCacheModel.externalImageCopyright = getExternalImageCopyright();

		String externalImageCopyright =
			projectCacheModel.externalImageCopyright;

		if ((externalImageCopyright != null) &&
			(externalImageCopyright.length() == 0)) {

			projectCacheModel.externalImageCopyright = null;
		}

		projectCacheModel.opacityImage = getOpacityImage();

		projectCacheModel.description = getDescription();

		String description = projectCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			projectCacheModel.description = null;
		}

		projectCacheModel.detailURL = getDetailURL();

		String detailURL = projectCacheModel.detailURL;

		if ((detailURL != null) && (detailURL.length() == 0)) {
			projectCacheModel.detailURL = null;
		}

		projectCacheModel.budget = getBudget();

		String budget = projectCacheModel.budget;

		if ((budget != null) && (budget.length() == 0)) {
			projectCacheModel.budget = null;
		}

		projectCacheModel.label = getLabel();

		String label = projectCacheModel.label;

		if ((label != null) && (label.length() == 0)) {
			projectCacheModel.label = null;
		}

		projectCacheModel.duration = getDuration();

		String duration = projectCacheModel.duration;

		if ((duration != null) && (duration.length() == 0)) {
			projectCacheModel.duration = null;
		}

		projectCacheModel.partners = getPartners();

		String partners = projectCacheModel.partners;

		if ((partners != null) && (partners.length() == 0)) {
			projectCacheModel.partners = null;
		}

		projectCacheModel.contactName = getContactName();

		String contactName = projectCacheModel.contactName;

		if ((contactName != null) && (contactName.length() == 0)) {
			projectCacheModel.contactName = null;
		}

		projectCacheModel.contactLine1 = getContactLine1();

		String contactLine1 = projectCacheModel.contactLine1;

		if ((contactLine1 != null) && (contactLine1.length() == 0)) {
			projectCacheModel.contactLine1 = null;
		}

		projectCacheModel.contactLine2 = getContactLine2();

		String contactLine2 = projectCacheModel.contactLine2;

		if ((contactLine2 != null) && (contactLine2.length() == 0)) {
			projectCacheModel.contactLine2 = null;
		}

		projectCacheModel.contactPhoneNumber = getContactPhoneNumber();

		String contactPhoneNumber = projectCacheModel.contactPhoneNumber;

		if ((contactPhoneNumber != null) &&
			(contactPhoneNumber.length() == 0)) {

			projectCacheModel.contactPhoneNumber = null;
		}

		projectCacheModel.imageId = getImageId();

		return projectCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Project, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Project, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Project, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Project)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Project, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Project, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Project, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Project)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Project>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _projectId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _title;
	private String _externalImageURL;
	private String _externalImageCopyright;
	private double _opacityImage;
	private String _description;
	private String _detailURL;
	private String _budget;
	private String _label;
	private String _duration;
	private String _partners;
	private String _contactName;
	private String _contactLine1;
	private String _contactLine2;
	private String _contactPhoneNumber;
	private long _imageId;
	private long _columnBitmask;
	private Project _escapedModel;

}