/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.edition.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.edition.model.EditionGallery;
import eu.strasbourg.service.edition.model.EditionGalleryModel;
import eu.strasbourg.service.edition.model.EditionGallerySoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EditionGallery service. Represents a row in the &quot;edition_EditionGallery&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>EditionGalleryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EditionGalleryImpl}.
 * </p>
 *
 * @author BenjaminBini
 * @see EditionGalleryImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class EditionGalleryModelImpl
	extends BaseModelImpl<EditionGallery> implements EditionGalleryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a edition gallery model instance should use the <code>EditionGallery</code> interface instead.
	 */
	public static final String TABLE_NAME = "edition_EditionGallery";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"galleryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"lastPublishDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"imageId", Types.BIGINT},
		{"title", Types.VARCHAR}, {"description", Types.CLOB},
		{"publicationDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("galleryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("imageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.CLOB);
		TABLE_COLUMNS_MAP.put("publicationDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table edition_EditionGallery (uuid_ VARCHAR(75) null,galleryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,lastPublishDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,imageId LONG,title STRING null,description TEXT null,publicationDate DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table edition_EditionGallery";

	public static final String ORDER_BY_JPQL =
		" ORDER BY editionGallery.title ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY edition_EditionGallery.title ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.edition.service.util.PropsUtil.get(
			"value.object.entity.cache.enabled.eu.strasbourg.service.edition.model.EditionGallery"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.edition.service.util.PropsUtil.get(
			"value.object.finder.cache.enabled.eu.strasbourg.service.edition.model.EditionGallery"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.edition.service.util.PropsUtil.get(
			"value.object.column.bitmask.enabled.eu.strasbourg.service.edition.model.EditionGallery"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long PUBLICATIONDATE_COLUMN_BITMASK = 4L;

	public static final long STATUS_COLUMN_BITMASK = 8L;

	public static final long TITLE_COLUMN_BITMASK = 16L;

	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EditionGallery toModel(EditionGallerySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EditionGallery model = new EditionGalleryImpl();

		model.setUuid(soapModel.getUuid());
		model.setGalleryId(soapModel.getGalleryId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setLastPublishDate(soapModel.getLastPublishDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setImageId(soapModel.getImageId());
		model.setTitle(soapModel.getTitle());
		model.setDescription(soapModel.getDescription());
		model.setPublicationDate(soapModel.getPublicationDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EditionGallery> toModels(
		EditionGallerySoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<EditionGallery> models = new ArrayList<EditionGallery>(
			soapModels.length);

		for (EditionGallerySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final String
		MAPPING_TABLE_EDITION_EDITIONTOEDITIONGALLERY_NAME =
			"edition_EditionToEditionGallery";

	public static final Object[][]
		MAPPING_TABLE_EDITION_EDITIONTOEDITIONGALLERY_COLUMNS = {
			{"companyId", Types.BIGINT}, {"editionId", Types.BIGINT},
			{"galleryId", Types.BIGINT}
		};

	public static final String
		MAPPING_TABLE_EDITION_EDITIONTOEDITIONGALLERY_SQL_CREATE =
			"create table edition_EditionToEditionGallery (companyId LONG not null,editionId LONG not null,galleryId LONG not null,primary key (editionId, galleryId))";

	public static final boolean
		FINDER_CACHE_ENABLED_EDITION_EDITIONTOEDITIONGALLERY =
			GetterUtil.getBoolean(
				eu.strasbourg.service.edition.service.util.PropsUtil.get(
					"value.object.finder.cache.enabled.edition_EditionToEditionGallery"),
				true);

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.edition.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.edition.model.EditionGallery"));

	public EditionGalleryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _galleryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGalleryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _galleryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EditionGallery.class;
	}

	@Override
	public String getModelClassName() {
		return EditionGallery.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EditionGallery, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EditionGallery, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EditionGallery, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EditionGallery)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EditionGallery, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EditionGallery, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EditionGallery)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EditionGallery, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EditionGallery, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, EditionGallery>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			EditionGallery.class.getClassLoader(), EditionGallery.class,
			ModelWrapper.class);

		try {
			Constructor<EditionGallery> constructor =
				(Constructor<EditionGallery>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<EditionGallery, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<EditionGallery, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<EditionGallery, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<EditionGallery, Object>>();
		Map<String, BiConsumer<EditionGallery, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<EditionGallery, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(EditionGallery editionGallery, Object uuid) {
					editionGallery.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"galleryId",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getGalleryId();
				}

			});
		attributeSetterBiConsumers.put(
			"galleryId",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object galleryId) {

					editionGallery.setGalleryId((Long)galleryId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object groupId) {

					editionGallery.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object companyId) {

					editionGallery.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object userId) {

					editionGallery.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object userName) {

					editionGallery.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object createDate) {

					editionGallery.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object modifiedDate) {

					editionGallery.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"lastPublishDate",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getLastPublishDate();
				}

			});
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object lastPublishDate) {

					editionGallery.setLastPublishDate((Date)lastPublishDate);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object status) {

					editionGallery.setStatus((Integer)status);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserId",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getStatusByUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserId",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object statusByUserId) {

					editionGallery.setStatusByUserId((Long)statusByUserId);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserName",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getStatusByUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserName",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object statusByUserName) {

					editionGallery.setStatusByUserName(
						(String)statusByUserName);
				}

			});
		attributeGetterFunctions.put(
			"statusDate",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getStatusDate();
				}

			});
		attributeSetterBiConsumers.put(
			"statusDate",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object statusDate) {

					editionGallery.setStatusDate((Date)statusDate);
				}

			});
		attributeGetterFunctions.put(
			"imageId",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getImageId();
				}

			});
		attributeSetterBiConsumers.put(
			"imageId",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object imageId) {

					editionGallery.setImageId((Long)imageId);
				}

			});
		attributeGetterFunctions.put(
			"title",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getTitle();
				}

			});
		attributeSetterBiConsumers.put(
			"title",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object title) {

					editionGallery.setTitle((String)title);
				}

			});
		attributeGetterFunctions.put(
			"description",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getDescription();
				}

			});
		attributeSetterBiConsumers.put(
			"description",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object description) {

					editionGallery.setDescription((String)description);
				}

			});
		attributeGetterFunctions.put(
			"publicationDate",
			new Function<EditionGallery, Object>() {

				@Override
				public Object apply(EditionGallery editionGallery) {
					return editionGallery.getPublicationDate();
				}

			});
		attributeSetterBiConsumers.put(
			"publicationDate",
			new BiConsumer<EditionGallery, Object>() {

				@Override
				public void accept(
					EditionGallery editionGallery, Object publicationDate) {

					editionGallery.setPublicationDate((Date)publicationDate);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getGalleryId() {
		return _galleryId;
	}

	@Override
	public void setGalleryId(long galleryId) {
		_galleryId = galleryId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public Long getImageId() {
		return _imageId;
	}

	@Override
	public void setImageId(Long imageId) {
		_imageId = imageId;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	@Override
	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	@Override
	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	@Override
	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTitle(), languageId, useDefault);
	}

	@Override
	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	@Override
	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	@Override
	public void setTitle(String title) {
		_columnBitmask = -1L;

		if (_originalTitle == null) {
			_originalTitle = _title;
		}

		_title = title;
	}

	@Override
	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(
				LocalizationUtil.updateLocalization(
					getTitle(), "Title", title, languageId, defaultLanguageId));
		}
		else {
			setTitle(
				LocalizationUtil.removeLocalization(
					getTitle(), "Title", languageId));
		}
	}

	@Override
	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitleMap(
		Map<Locale, String> titleMap, Locale defaultLocale) {

		if (titleMap == null) {
			return;
		}

		setTitle(
			LocalizationUtil.updateLocalization(
				titleMap, getTitle(), "Title",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	public String getOriginalTitle() {
		return GetterUtil.getString(_originalTitle);
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public Date getPublicationDate() {
		return _publicationDate;
	}

	@Override
	public void setPublicationDate(Date publicationDate) {
		_columnBitmask |= PUBLICATIONDATE_COLUMN_BITMASK;

		if (_originalPublicationDate == null) {
			_originalPublicationDate = _publicationDate;
		}

		_publicationDate = publicationDate;
	}

	public Date getOriginalPublicationDate() {
		return _originalPublicationDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EditionGallery.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EditionGallery.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> titleMap = getTitleMap();

		for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTitle();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			EditionGallery.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String title = getTitle(defaultLocale);

		if (Validator.isNull(title)) {
			setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public EditionGallery toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EditionGalleryImpl editionGalleryImpl = new EditionGalleryImpl();

		editionGalleryImpl.setUuid(getUuid());
		editionGalleryImpl.setGalleryId(getGalleryId());
		editionGalleryImpl.setGroupId(getGroupId());
		editionGalleryImpl.setCompanyId(getCompanyId());
		editionGalleryImpl.setUserId(getUserId());
		editionGalleryImpl.setUserName(getUserName());
		editionGalleryImpl.setCreateDate(getCreateDate());
		editionGalleryImpl.setModifiedDate(getModifiedDate());
		editionGalleryImpl.setLastPublishDate(getLastPublishDate());
		editionGalleryImpl.setStatus(getStatus());
		editionGalleryImpl.setStatusByUserId(getStatusByUserId());
		editionGalleryImpl.setStatusByUserName(getStatusByUserName());
		editionGalleryImpl.setStatusDate(getStatusDate());
		editionGalleryImpl.setImageId(getImageId());
		editionGalleryImpl.setTitle(getTitle());
		editionGalleryImpl.setDescription(getDescription());
		editionGalleryImpl.setPublicationDate(getPublicationDate());

		editionGalleryImpl.resetOriginalValues();

		return editionGalleryImpl;
	}

	@Override
	public int compareTo(EditionGallery editionGallery) {
		int value = 0;

		value = getTitle().compareTo(editionGallery.getTitle());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EditionGallery)) {
			return false;
		}

		EditionGallery editionGallery = (EditionGallery)obj;

		long primaryKey = editionGallery.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		EditionGalleryModelImpl editionGalleryModelImpl = this;

		editionGalleryModelImpl._originalUuid = editionGalleryModelImpl._uuid;

		editionGalleryModelImpl._originalGroupId =
			editionGalleryModelImpl._groupId;

		editionGalleryModelImpl._setOriginalGroupId = false;

		editionGalleryModelImpl._originalCompanyId =
			editionGalleryModelImpl._companyId;

		editionGalleryModelImpl._setOriginalCompanyId = false;

		editionGalleryModelImpl._setModifiedDate = false;

		editionGalleryModelImpl._originalStatus =
			editionGalleryModelImpl._status;

		editionGalleryModelImpl._setOriginalStatus = false;

		editionGalleryModelImpl._originalTitle = editionGalleryModelImpl._title;

		editionGalleryModelImpl._originalPublicationDate =
			editionGalleryModelImpl._publicationDate;

		editionGalleryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EditionGallery> toCacheModel() {
		EditionGalleryCacheModel editionGalleryCacheModel =
			new EditionGalleryCacheModel();

		editionGalleryCacheModel.uuid = getUuid();

		String uuid = editionGalleryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			editionGalleryCacheModel.uuid = null;
		}

		editionGalleryCacheModel.galleryId = getGalleryId();

		editionGalleryCacheModel.groupId = getGroupId();

		editionGalleryCacheModel.companyId = getCompanyId();

		editionGalleryCacheModel.userId = getUserId();

		editionGalleryCacheModel.userName = getUserName();

		String userName = editionGalleryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			editionGalleryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			editionGalleryCacheModel.createDate = createDate.getTime();
		}
		else {
			editionGalleryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			editionGalleryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			editionGalleryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			editionGalleryCacheModel.lastPublishDate =
				lastPublishDate.getTime();
		}
		else {
			editionGalleryCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		editionGalleryCacheModel.status = getStatus();

		editionGalleryCacheModel.statusByUserId = getStatusByUserId();

		editionGalleryCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = editionGalleryCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			editionGalleryCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			editionGalleryCacheModel.statusDate = statusDate.getTime();
		}
		else {
			editionGalleryCacheModel.statusDate = Long.MIN_VALUE;
		}

		editionGalleryCacheModel.imageId = getImageId();

		editionGalleryCacheModel.title = getTitle();

		String title = editionGalleryCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			editionGalleryCacheModel.title = null;
		}

		editionGalleryCacheModel.description = getDescription();

		String description = editionGalleryCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			editionGalleryCacheModel.description = null;
		}

		Date publicationDate = getPublicationDate();

		if (publicationDate != null) {
			editionGalleryCacheModel.publicationDate =
				publicationDate.getTime();
		}
		else {
			editionGalleryCacheModel.publicationDate = Long.MIN_VALUE;
		}

		return editionGalleryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EditionGallery, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EditionGallery, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EditionGallery, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((EditionGallery)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<EditionGallery, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<EditionGallery, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EditionGallery, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((EditionGallery)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, EditionGallery>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private String _uuid;
	private String _originalUuid;
	private long _galleryId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _lastPublishDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private Long _imageId;
	private String _title;
	private String _titleCurrentLanguageId;
	private String _originalTitle;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private Date _publicationDate;
	private Date _originalPublicationDate;
	private long _columnBitmask;
	private EditionGallery _escapedModel;

}