/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.strasbourg.model.impl;

import aQute.bnd.annotation.ProviderType;

import eu.strasbourg.service.strasbourg.model.Strasbourg;
import eu.strasbourg.service.strasbourg.service.StrasbourgLocalServiceUtil;

/**
 * The extended model base implementation for the Strasbourg service. Represents a row in the &quot;strasbourg_Strasbourg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StrasbourgImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StrasbourgImpl
 * @see Strasbourg
 * @generated
 */
@ProviderType
public abstract class StrasbourgBaseImpl extends StrasbourgModelImpl
	implements Strasbourg {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a strasbourg model instance should use the {@link Strasbourg} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			StrasbourgLocalServiceUtil.addStrasbourg(this);
		}
		else {
			StrasbourgLocalServiceUtil.updateStrasbourg(this);
		}
	}
}