/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.gtfs.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import eu.strasbourg.service.gtfs.model.Agency;
import eu.strasbourg.service.gtfs.model.AgencyModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Agency service. Represents a row in the &quot;gtfs_Agency&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AgencyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AgencyImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see AgencyImpl
 * @see Agency
 * @see AgencyModel
 * @generated
 */
@ProviderType
public class AgencyModelImpl extends BaseModelImpl<Agency>
	implements AgencyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a agency model instance should use the {@link Agency} interface instead.
	 */
	public static final String TABLE_NAME = "gtfs_Agency";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "id_", Types.BIGINT },
			{ "agency_name", Types.VARCHAR },
			{ "agency_url", Types.VARCHAR },
			{ "agency_timezone", Types.VARCHAR },
			{ "agency_phone", Types.VARCHAR },
			{ "agency_fare_url", Types.VARCHAR },
			{ "agency_lang", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("agency_name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("agency_url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("agency_timezone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("agency_phone", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("agency_fare_url", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("agency_lang", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table gtfs_Agency (uuid_ VARCHAR(75) null,id_ LONG not null primary key,agency_name VARCHAR(75) null,agency_url VARCHAR(400) null,agency_timezone VARCHAR(75) null,agency_phone VARCHAR(75) null,agency_fare_url VARCHAR(400) null,agency_lang VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table gtfs_Agency";
	public static final String ORDER_BY_JPQL = " ORDER BY agency.agency_name ASC";
	public static final String ORDER_BY_SQL = " ORDER BY gtfs_Agency.agency_name ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(eu.strasbourg.service.project.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.eu.strasbourg.service.gtfs.model.Agency"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(eu.strasbourg.service.project.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.eu.strasbourg.service.gtfs.model.Agency"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(eu.strasbourg.service.project.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.eu.strasbourg.service.gtfs.model.Agency"),
			true);
	public static final long UUID_COLUMN_BITMASK = 1L;
	public static final long AGENCY_NAME_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(eu.strasbourg.service.project.service.util.PropsUtil.get(
				"lock.expiration.time.eu.strasbourg.service.gtfs.model.Agency"));

	public AgencyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Agency.class;
	}

	@Override
	public String getModelClassName() {
		return Agency.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("id", getId());
		attributes.put("agency_name", getAgency_name());
		attributes.put("agency_url", getAgency_url());
		attributes.put("agency_timezone", getAgency_timezone());
		attributes.put("agency_phone", getAgency_phone());
		attributes.put("agency_fare_url", getAgency_fare_url());
		attributes.put("agency_lang", getAgency_lang());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String agency_name = (String)attributes.get("agency_name");

		if (agency_name != null) {
			setAgency_name(agency_name);
		}

		String agency_url = (String)attributes.get("agency_url");

		if (agency_url != null) {
			setAgency_url(agency_url);
		}

		String agency_timezone = (String)attributes.get("agency_timezone");

		if (agency_timezone != null) {
			setAgency_timezone(agency_timezone);
		}

		String agency_phone = (String)attributes.get("agency_phone");

		if (agency_phone != null) {
			setAgency_phone(agency_phone);
		}

		String agency_fare_url = (String)attributes.get("agency_fare_url");

		if (agency_fare_url != null) {
			setAgency_fare_url(agency_fare_url);
		}

		String agency_lang = (String)attributes.get("agency_lang");

		if (agency_lang != null) {
			setAgency_lang(agency_lang);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getAgency_name() {
		if (_agency_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _agency_name;
		}
	}

	@Override
	public void setAgency_name(String agency_name) {
		_columnBitmask = -1L;

		_agency_name = agency_name;
	}

	@Override
	public String getAgency_url() {
		if (_agency_url == null) {
			return StringPool.BLANK;
		}
		else {
			return _agency_url;
		}
	}

	@Override
	public void setAgency_url(String agency_url) {
		_agency_url = agency_url;
	}

	@Override
	public String getAgency_timezone() {
		if (_agency_timezone == null) {
			return StringPool.BLANK;
		}
		else {
			return _agency_timezone;
		}
	}

	@Override
	public void setAgency_timezone(String agency_timezone) {
		_agency_timezone = agency_timezone;
	}

	@Override
	public String getAgency_phone() {
		if (_agency_phone == null) {
			return StringPool.BLANK;
		}
		else {
			return _agency_phone;
		}
	}

	@Override
	public void setAgency_phone(String agency_phone) {
		_agency_phone = agency_phone;
	}

	@Override
	public String getAgency_fare_url() {
		if (_agency_fare_url == null) {
			return StringPool.BLANK;
		}
		else {
			return _agency_fare_url;
		}
	}

	@Override
	public void setAgency_fare_url(String agency_fare_url) {
		_agency_fare_url = agency_fare_url;
	}

	@Override
	public String getAgency_lang() {
		if (_agency_lang == null) {
			return StringPool.BLANK;
		}
		else {
			return _agency_lang;
		}
	}

	@Override
	public void setAgency_lang(String agency_lang) {
		_agency_lang = agency_lang;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Agency.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Agency toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Agency)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AgencyImpl agencyImpl = new AgencyImpl();

		agencyImpl.setUuid(getUuid());
		agencyImpl.setId(getId());
		agencyImpl.setAgency_name(getAgency_name());
		agencyImpl.setAgency_url(getAgency_url());
		agencyImpl.setAgency_timezone(getAgency_timezone());
		agencyImpl.setAgency_phone(getAgency_phone());
		agencyImpl.setAgency_fare_url(getAgency_fare_url());
		agencyImpl.setAgency_lang(getAgency_lang());

		agencyImpl.resetOriginalValues();

		return agencyImpl;
	}

	@Override
	public int compareTo(Agency agency) {
		int value = 0;

		value = getAgency_name().compareTo(agency.getAgency_name());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Agency)) {
			return false;
		}

		Agency agency = (Agency)obj;

		long primaryKey = agency.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AgencyModelImpl agencyModelImpl = this;

		agencyModelImpl._originalUuid = agencyModelImpl._uuid;

		agencyModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Agency> toCacheModel() {
		AgencyCacheModel agencyCacheModel = new AgencyCacheModel();

		agencyCacheModel.uuid = getUuid();

		String uuid = agencyCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			agencyCacheModel.uuid = null;
		}

		agencyCacheModel.id = getId();

		agencyCacheModel.agency_name = getAgency_name();

		String agency_name = agencyCacheModel.agency_name;

		if ((agency_name != null) && (agency_name.length() == 0)) {
			agencyCacheModel.agency_name = null;
		}

		agencyCacheModel.agency_url = getAgency_url();

		String agency_url = agencyCacheModel.agency_url;

		if ((agency_url != null) && (agency_url.length() == 0)) {
			agencyCacheModel.agency_url = null;
		}

		agencyCacheModel.agency_timezone = getAgency_timezone();

		String agency_timezone = agencyCacheModel.agency_timezone;

		if ((agency_timezone != null) && (agency_timezone.length() == 0)) {
			agencyCacheModel.agency_timezone = null;
		}

		agencyCacheModel.agency_phone = getAgency_phone();

		String agency_phone = agencyCacheModel.agency_phone;

		if ((agency_phone != null) && (agency_phone.length() == 0)) {
			agencyCacheModel.agency_phone = null;
		}

		agencyCacheModel.agency_fare_url = getAgency_fare_url();

		String agency_fare_url = agencyCacheModel.agency_fare_url;

		if ((agency_fare_url != null) && (agency_fare_url.length() == 0)) {
			agencyCacheModel.agency_fare_url = null;
		}

		agencyCacheModel.agency_lang = getAgency_lang();

		String agency_lang = agencyCacheModel.agency_lang;

		if ((agency_lang != null) && (agency_lang.length() == 0)) {
			agencyCacheModel.agency_lang = null;
		}

		return agencyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", id=");
		sb.append(getId());
		sb.append(", agency_name=");
		sb.append(getAgency_name());
		sb.append(", agency_url=");
		sb.append(getAgency_url());
		sb.append(", agency_timezone=");
		sb.append(getAgency_timezone());
		sb.append(", agency_phone=");
		sb.append(getAgency_phone());
		sb.append(", agency_fare_url=");
		sb.append(getAgency_fare_url());
		sb.append(", agency_lang=");
		sb.append(getAgency_lang());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("eu.strasbourg.service.gtfs.model.Agency");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>agency_name</column-name><column-value><![CDATA[");
		sb.append(getAgency_name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>agency_url</column-name><column-value><![CDATA[");
		sb.append(getAgency_url());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>agency_timezone</column-name><column-value><![CDATA[");
		sb.append(getAgency_timezone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>agency_phone</column-name><column-value><![CDATA[");
		sb.append(getAgency_phone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>agency_fare_url</column-name><column-value><![CDATA[");
		sb.append(getAgency_fare_url());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>agency_lang</column-name><column-value><![CDATA[");
		sb.append(getAgency_lang());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Agency.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Agency.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _id;
	private String _agency_name;
	private String _agency_url;
	private String _agency_timezone;
	private String _agency_phone;
	private String _agency_fare_url;
	private String _agency_lang;
	private long _columnBitmask;
	private Agency _escapedModel;
}