/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.gtfs.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import eu.strasbourg.service.gtfs.model.Trip;
import eu.strasbourg.service.gtfs.model.TripModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Trip service. Represents a row in the &quot;gtfs_Trip&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TripModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TripImpl}.
 * </p>
 *
 * @author Cedric Henry
 * @see TripImpl
 * @see Trip
 * @see TripModel
 * @generated
 */
@ProviderType
public class TripModelImpl extends BaseModelImpl<Trip> implements TripModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a trip model instance should use the {@link Trip} interface instead.
	 */
	public static final String TABLE_NAME = "gtfs_Trip";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "id_", Types.BIGINT },
			{ "route_id", Types.VARCHAR },
			{ "service_id", Types.VARCHAR },
			{ "trip_id", Types.VARCHAR },
			{ "trip_headsign", Types.VARCHAR },
			{ "direction_id", Types.BOOLEAN },
			{ "block_id", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("route_id", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("service_id", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("trip_id", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("trip_headsign", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("direction_id", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("block_id", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table gtfs_Trip (uuid_ VARCHAR(75) null,id_ LONG not null primary key,route_id VARCHAR(75) null,service_id VARCHAR(75) null,trip_id VARCHAR(75) null,trip_headsign VARCHAR(75) null,direction_id BOOLEAN,block_id VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table gtfs_Trip";
	public static final String ORDER_BY_JPQL = " ORDER BY trip.trip_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY gtfs_Trip.trip_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(eu.strasbourg.service.gtfs.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.eu.strasbourg.service.gtfs.model.Trip"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(eu.strasbourg.service.gtfs.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.eu.strasbourg.service.gtfs.model.Trip"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(eu.strasbourg.service.gtfs.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.eu.strasbourg.service.gtfs.model.Trip"),
			true);
	public static final long UUID_COLUMN_BITMASK = 1L;
	public static final long TRIP_ID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(eu.strasbourg.service.gtfs.service.util.PropsUtil.get(
				"lock.expiration.time.eu.strasbourg.service.gtfs.model.Trip"));

	public TripModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Trip.class;
	}

	@Override
	public String getModelClassName() {
		return Trip.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("id", getId());
		attributes.put("route_id", getRoute_id());
		attributes.put("service_id", getService_id());
		attributes.put("trip_id", getTrip_id());
		attributes.put("trip_headsign", getTrip_headsign());
		attributes.put("direction_id", getDirection_id());
		attributes.put("block_id", getBlock_id());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String route_id = (String)attributes.get("route_id");

		if (route_id != null) {
			setRoute_id(route_id);
		}

		String service_id = (String)attributes.get("service_id");

		if (service_id != null) {
			setService_id(service_id);
		}

		String trip_id = (String)attributes.get("trip_id");

		if (trip_id != null) {
			setTrip_id(trip_id);
		}

		String trip_headsign = (String)attributes.get("trip_headsign");

		if (trip_headsign != null) {
			setTrip_headsign(trip_headsign);
		}

		Boolean direction_id = (Boolean)attributes.get("direction_id");

		if (direction_id != null) {
			setDirection_id(direction_id);
		}

		String block_id = (String)attributes.get("block_id");

		if (block_id != null) {
			setBlock_id(block_id);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public String getRoute_id() {
		if (_route_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _route_id;
		}
	}

	@Override
	public void setRoute_id(String route_id) {
		_route_id = route_id;
	}

	@Override
	public String getService_id() {
		if (_service_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _service_id;
		}
	}

	@Override
	public void setService_id(String service_id) {
		_service_id = service_id;
	}

	@Override
	public String getTrip_id() {
		if (_trip_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _trip_id;
		}
	}

	@Override
	public void setTrip_id(String trip_id) {
		_columnBitmask = -1L;

		_trip_id = trip_id;
	}

	@Override
	public String getTrip_headsign() {
		if (_trip_headsign == null) {
			return StringPool.BLANK;
		}
		else {
			return _trip_headsign;
		}
	}

	@Override
	public void setTrip_headsign(String trip_headsign) {
		_trip_headsign = trip_headsign;
	}

	@Override
	public boolean getDirection_id() {
		return _direction_id;
	}

	@Override
	public boolean isDirection_id() {
		return _direction_id;
	}

	@Override
	public void setDirection_id(boolean direction_id) {
		_direction_id = direction_id;
	}

	@Override
	public String getBlock_id() {
		if (_block_id == null) {
			return StringPool.BLANK;
		}
		else {
			return _block_id;
		}
	}

	@Override
	public void setBlock_id(String block_id) {
		_block_id = block_id;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Trip.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Trip toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Trip)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TripImpl tripImpl = new TripImpl();

		tripImpl.setUuid(getUuid());
		tripImpl.setId(getId());
		tripImpl.setRoute_id(getRoute_id());
		tripImpl.setService_id(getService_id());
		tripImpl.setTrip_id(getTrip_id());
		tripImpl.setTrip_headsign(getTrip_headsign());
		tripImpl.setDirection_id(getDirection_id());
		tripImpl.setBlock_id(getBlock_id());

		tripImpl.resetOriginalValues();

		return tripImpl;
	}

	@Override
	public int compareTo(Trip trip) {
		int value = 0;

		value = getTrip_id().compareTo(trip.getTrip_id());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Trip)) {
			return false;
		}

		Trip trip = (Trip)obj;

		long primaryKey = trip.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TripModelImpl tripModelImpl = this;

		tripModelImpl._originalUuid = tripModelImpl._uuid;

		tripModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Trip> toCacheModel() {
		TripCacheModel tripCacheModel = new TripCacheModel();

		tripCacheModel.uuid = getUuid();

		String uuid = tripCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			tripCacheModel.uuid = null;
		}

		tripCacheModel.id = getId();

		tripCacheModel.route_id = getRoute_id();

		String route_id = tripCacheModel.route_id;

		if ((route_id != null) && (route_id.length() == 0)) {
			tripCacheModel.route_id = null;
		}

		tripCacheModel.service_id = getService_id();

		String service_id = tripCacheModel.service_id;

		if ((service_id != null) && (service_id.length() == 0)) {
			tripCacheModel.service_id = null;
		}

		tripCacheModel.trip_id = getTrip_id();

		String trip_id = tripCacheModel.trip_id;

		if ((trip_id != null) && (trip_id.length() == 0)) {
			tripCacheModel.trip_id = null;
		}

		tripCacheModel.trip_headsign = getTrip_headsign();

		String trip_headsign = tripCacheModel.trip_headsign;

		if ((trip_headsign != null) && (trip_headsign.length() == 0)) {
			tripCacheModel.trip_headsign = null;
		}

		tripCacheModel.direction_id = getDirection_id();

		tripCacheModel.block_id = getBlock_id();

		String block_id = tripCacheModel.block_id;

		if ((block_id != null) && (block_id.length() == 0)) {
			tripCacheModel.block_id = null;
		}

		return tripCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", id=");
		sb.append(getId());
		sb.append(", route_id=");
		sb.append(getRoute_id());
		sb.append(", service_id=");
		sb.append(getService_id());
		sb.append(", trip_id=");
		sb.append(getTrip_id());
		sb.append(", trip_headsign=");
		sb.append(getTrip_headsign());
		sb.append(", direction_id=");
		sb.append(getDirection_id());
		sb.append(", block_id=");
		sb.append(getBlock_id());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("eu.strasbourg.service.gtfs.model.Trip");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>route_id</column-name><column-value><![CDATA[");
		sb.append(getRoute_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>service_id</column-name><column-value><![CDATA[");
		sb.append(getService_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trip_id</column-name><column-value><![CDATA[");
		sb.append(getTrip_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trip_headsign</column-name><column-value><![CDATA[");
		sb.append(getTrip_headsign());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>direction_id</column-name><column-value><![CDATA[");
		sb.append(getDirection_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>block_id</column-name><column-value><![CDATA[");
		sb.append(getBlock_id());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Trip.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Trip.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _id;
	private String _route_id;
	private String _service_id;
	private String _trip_id;
	private String _trip_headsign;
	private boolean _direction_id;
	private String _block_id;
	private long _columnBitmask;
	private Trip _escapedModel;
}