create table project_Participation (
	uuid_ varchar(75) null,
	participationId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate timestamp null,
	modifiedDate timestamp null,
	status integer,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate timestamp null,
	title varchar(400) null,
	author varchar(75) null,
	contactName varchar(75) null,
	contactLine1 varchar(400) null,
	contactLine2 varchar(400) null,
	contactPhoneNumber varchar(75) null,
	publicationDate timestamp null,
	expirationDate timestamp null
);

create table project_Project (
	uuid_ varchar(75) null,
	projectId bigint not null primary key,
	groupId bigint,
	companyId bigint,
	userId bigint,
	userName varchar(75) null,
	createDate timestamp null,
	modifiedDate timestamp null,
	status integer,
	statusByUserId bigint,
	statusByUserName varchar(75) null,
	statusDate timestamp null,
	title varchar(400) null,
	externalImageURL varchar(75) null,
	externalImageCopyright varchar(75) null,
	imageWidth integer,
	imageHeight integer,
	description text null,
	budget varchar(75) null,
	label varchar(75) null,
	duration integer,
	partners text null,
	contactName varchar(75) null,
	contactLine1 varchar(400) null,
	contactLine2 varchar(400) null,
	contactPhoneNumber varchar(75) null,
	imageId bigint
);

create table project_ProjectTimeline (
	projectTimelineId bigint not null primary key,
	startDay integer,
	date_ timestamp null,
	title varchar(400) null,
	projectId bigint
);
