/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.agenda.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import eu.strasbourg.service.agenda.model.Campaign;
import eu.strasbourg.service.agenda.model.CampaignModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Campaign service. Represents a row in the &quot;agenda_Campaign&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CampaignModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CampaignImpl}.
 * </p>
 *
 * @author BenjaminBini
 * @see CampaignImpl
 * @generated
 */
public class CampaignModelImpl
	extends BaseModelImpl<Campaign> implements CampaignModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a campaign model instance should use the <code>Campaign</code> interface instead.
	 */
	public static final String TABLE_NAME = "agenda_Campaign";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"campaignId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"lastPublishDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}, {"title", Types.VARCHAR},
		{"defaultImageId", Types.BIGINT},
		{"defaultImageCopyright", Types.VARCHAR},
		{"managersIds", Types.VARCHAR}, {"exportEnabled", Types.BOOLEAN},
		{"startDate", Types.TIMESTAMP}, {"endDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("campaignId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("defaultImageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("defaultImageCopyright", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("managersIds", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("exportEnabled", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table agenda_Campaign (uuid_ VARCHAR(75) null,campaignId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,lastPublishDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,title STRING null,defaultImageId LONG,defaultImageCopyright STRING null,managersIds VARCHAR(75) null,exportEnabled BOOLEAN,startDate DATE null,endDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table agenda_Campaign";

	public static final String ORDER_BY_JPQL =
		" ORDER BY campaign.modifiedDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY agenda_Campaign.modifiedDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.agenda.service.util.PropsUtil.get(
			"value.object.entity.cache.enabled.eu.strasbourg.service.agenda.model.Campaign"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.agenda.service.util.PropsUtil.get(
			"value.object.finder.cache.enabled.eu.strasbourg.service.agenda.model.Campaign"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.agenda.service.util.PropsUtil.get(
			"value.object.column.bitmask.enabled.eu.strasbourg.service.agenda.model.Campaign"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long TITLE_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long MODIFIEDDATE_COLUMN_BITMASK = 16L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.agenda.service.util.PropsUtil.get(
			"lock.expiration.time.eu.strasbourg.service.agenda.model.Campaign"));

	public CampaignModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _campaignId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCampaignId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _campaignId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Campaign.class;
	}

	@Override
	public String getModelClassName() {
		return Campaign.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Campaign, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Campaign, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Campaign, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Campaign)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Campaign, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Campaign, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Campaign)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Campaign, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Campaign, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Campaign>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Campaign.class.getClassLoader(), Campaign.class,
			ModelWrapper.class);

		try {
			Constructor<Campaign> constructor =
				(Constructor<Campaign>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Campaign, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Campaign, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Campaign, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Campaign, Object>>();
		Map<String, BiConsumer<Campaign, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Campaign, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(Campaign campaign, Object uuidObject) {
					campaign.setUuid((String)uuidObject);
				}

			});
		attributeGetterFunctions.put(
			"campaignId",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getCampaignId();
				}

			});
		attributeSetterBiConsumers.put(
			"campaignId",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(Campaign campaign, Object campaignIdObject) {
					campaign.setCampaignId((Long)campaignIdObject);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(Campaign campaign, Object groupIdObject) {
					campaign.setGroupId((Long)groupIdObject);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(Campaign campaign, Object companyIdObject) {
					campaign.setCompanyId((Long)companyIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(Campaign campaign, Object userIdObject) {
					campaign.setUserId((Long)userIdObject);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(Campaign campaign, Object userNameObject) {
					campaign.setUserName((String)userNameObject);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(Campaign campaign, Object createDateObject) {
					campaign.setCreateDate((Date)createDateObject);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(
					Campaign campaign, Object modifiedDateObject) {

					campaign.setModifiedDate((Date)modifiedDateObject);
				}

			});
		attributeGetterFunctions.put(
			"lastPublishDate",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getLastPublishDate();
				}

			});
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(
					Campaign campaign, Object lastPublishDateObject) {

					campaign.setLastPublishDate((Date)lastPublishDateObject);
				}

			});
		attributeGetterFunctions.put(
			"status",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getStatus();
				}

			});
		attributeSetterBiConsumers.put(
			"status",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(Campaign campaign, Object statusObject) {
					campaign.setStatus((Integer)statusObject);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserId",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getStatusByUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserId",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(
					Campaign campaign, Object statusByUserIdObject) {

					campaign.setStatusByUserId((Long)statusByUserIdObject);
				}

			});
		attributeGetterFunctions.put(
			"statusByUserName",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getStatusByUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"statusByUserName",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(
					Campaign campaign, Object statusByUserNameObject) {

					campaign.setStatusByUserName(
						(String)statusByUserNameObject);
				}

			});
		attributeGetterFunctions.put(
			"statusDate",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getStatusDate();
				}

			});
		attributeSetterBiConsumers.put(
			"statusDate",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(Campaign campaign, Object statusDateObject) {
					campaign.setStatusDate((Date)statusDateObject);
				}

			});
		attributeGetterFunctions.put(
			"title",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getTitle();
				}

			});
		attributeSetterBiConsumers.put(
			"title",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(Campaign campaign, Object titleObject) {
					campaign.setTitle((String)titleObject);
				}

			});
		attributeGetterFunctions.put(
			"defaultImageId",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getDefaultImageId();
				}

			});
		attributeSetterBiConsumers.put(
			"defaultImageId",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(
					Campaign campaign, Object defaultImageIdObject) {

					campaign.setDefaultImageId((Long)defaultImageIdObject);
				}

			});
		attributeGetterFunctions.put(
			"defaultImageCopyright",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getDefaultImageCopyright();
				}

			});
		attributeSetterBiConsumers.put(
			"defaultImageCopyright",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(
					Campaign campaign, Object defaultImageCopyrightObject) {

					campaign.setDefaultImageCopyright(
						(String)defaultImageCopyrightObject);
				}

			});
		attributeGetterFunctions.put(
			"managersIds",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getManagersIds();
				}

			});
		attributeSetterBiConsumers.put(
			"managersIds",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(
					Campaign campaign, Object managersIdsObject) {

					campaign.setManagersIds((String)managersIdsObject);
				}

			});
		attributeGetterFunctions.put(
			"exportEnabled",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getExportEnabled();
				}

			});
		attributeSetterBiConsumers.put(
			"exportEnabled",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(
					Campaign campaign, Object exportEnabledObject) {

					campaign.setExportEnabled((Boolean)exportEnabledObject);
				}

			});
		attributeGetterFunctions.put(
			"startDate",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getStartDate();
				}

			});
		attributeSetterBiConsumers.put(
			"startDate",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(Campaign campaign, Object startDateObject) {
					campaign.setStartDate((Date)startDateObject);
				}

			});
		attributeGetterFunctions.put(
			"endDate",
			new Function<Campaign, Object>() {

				@Override
				public Object apply(Campaign campaign) {
					return campaign.getEndDate();
				}

			});
		attributeSetterBiConsumers.put(
			"endDate",
			new BiConsumer<Campaign, Object>() {

				@Override
				public void accept(Campaign campaign, Object endDateObject) {
					campaign.setEndDate((Date)endDateObject);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getCampaignId() {
		return _campaignId;
	}

	@Override
	public void setCampaignId(long campaignId) {
		_campaignId = campaignId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_lastPublishDate = lastPublishDate;
	}

	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_status = status;
	}

	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public String getTitle(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId);
	}

	@Override
	public String getTitle(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTitle(languageId, useDefault);
	}

	@Override
	public String getTitle(String languageId) {
		return LocalizationUtil.getLocalization(getTitle(), languageId);
	}

	@Override
	public String getTitle(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getTitle(), languageId, useDefault);
	}

	@Override
	public String getTitleCurrentLanguageId() {
		return _titleCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTitleCurrentValue() {
		Locale locale = getLocale(_titleCurrentLanguageId);

		return getTitle(locale);
	}

	@Override
	public Map<Locale, String> getTitleMap() {
		return LocalizationUtil.getLocalizationMap(getTitle());
	}

	@Override
	public void setTitle(String title) {
		_columnBitmask |= TITLE_COLUMN_BITMASK;

		if (_originalTitle == null) {
			_originalTitle = _title;
		}

		_title = title;
	}

	@Override
	public void setTitle(String title, Locale locale) {
		setTitle(title, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitle(String title, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(title)) {
			setTitle(
				LocalizationUtil.updateLocalization(
					getTitle(), "Title", title, languageId, defaultLanguageId));
		}
		else {
			setTitle(
				LocalizationUtil.removeLocalization(
					getTitle(), "Title", languageId));
		}
	}

	@Override
	public void setTitleCurrentLanguageId(String languageId) {
		_titleCurrentLanguageId = languageId;
	}

	@Override
	public void setTitleMap(Map<Locale, String> titleMap) {
		setTitleMap(titleMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setTitleMap(
		Map<Locale, String> titleMap, Locale defaultLocale) {

		if (titleMap == null) {
			return;
		}

		setTitle(
			LocalizationUtil.updateLocalization(
				titleMap, getTitle(), "Title",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	public String getOriginalTitle() {
		return GetterUtil.getString(_originalTitle);
	}

	@Override
	public long getDefaultImageId() {
		return _defaultImageId;
	}

	@Override
	public void setDefaultImageId(long defaultImageId) {
		_defaultImageId = defaultImageId;
	}

	@Override
	public String getDefaultImageCopyright() {
		if (_defaultImageCopyright == null) {
			return "";
		}
		else {
			return _defaultImageCopyright;
		}
	}

	@Override
	public String getDefaultImageCopyright(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDefaultImageCopyright(languageId);
	}

	@Override
	public String getDefaultImageCopyright(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDefaultImageCopyright(languageId, useDefault);
	}

	@Override
	public String getDefaultImageCopyright(String languageId) {
		return LocalizationUtil.getLocalization(
			getDefaultImageCopyright(), languageId);
	}

	@Override
	public String getDefaultImageCopyright(
		String languageId, boolean useDefault) {

		return LocalizationUtil.getLocalization(
			getDefaultImageCopyright(), languageId, useDefault);
	}

	@Override
	public String getDefaultImageCopyrightCurrentLanguageId() {
		return _defaultImageCopyrightCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDefaultImageCopyrightCurrentValue() {
		Locale locale = getLocale(_defaultImageCopyrightCurrentLanguageId);

		return getDefaultImageCopyright(locale);
	}

	@Override
	public Map<Locale, String> getDefaultImageCopyrightMap() {
		return LocalizationUtil.getLocalizationMap(getDefaultImageCopyright());
	}

	@Override
	public void setDefaultImageCopyright(String defaultImageCopyright) {
		_defaultImageCopyright = defaultImageCopyright;
	}

	@Override
	public void setDefaultImageCopyright(
		String defaultImageCopyright, Locale locale) {

		setDefaultImageCopyright(
			defaultImageCopyright, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDefaultImageCopyright(
		String defaultImageCopyright, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(defaultImageCopyright)) {
			setDefaultImageCopyright(
				LocalizationUtil.updateLocalization(
					getDefaultImageCopyright(), "DefaultImageCopyright",
					defaultImageCopyright, languageId, defaultLanguageId));
		}
		else {
			setDefaultImageCopyright(
				LocalizationUtil.removeLocalization(
					getDefaultImageCopyright(), "DefaultImageCopyright",
					languageId));
		}
	}

	@Override
	public void setDefaultImageCopyrightCurrentLanguageId(String languageId) {
		_defaultImageCopyrightCurrentLanguageId = languageId;
	}

	@Override
	public void setDefaultImageCopyrightMap(
		Map<Locale, String> defaultImageCopyrightMap) {

		setDefaultImageCopyrightMap(
			defaultImageCopyrightMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDefaultImageCopyrightMap(
		Map<Locale, String> defaultImageCopyrightMap, Locale defaultLocale) {

		if (defaultImageCopyrightMap == null) {
			return;
		}

		setDefaultImageCopyright(
			LocalizationUtil.updateLocalization(
				defaultImageCopyrightMap, getDefaultImageCopyright(),
				"DefaultImageCopyright",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@Override
	public String getManagersIds() {
		if (_managersIds == null) {
			return "";
		}
		else {
			return _managersIds;
		}
	}

	@Override
	public void setManagersIds(String managersIds) {
		_managersIds = managersIds;
	}

	@Override
	public Boolean getExportEnabled() {
		return _exportEnabled;
	}

	@Override
	public void setExportEnabled(Boolean exportEnabled) {
		_exportEnabled = exportEnabled;
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_endDate = endDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Campaign.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Campaign.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> titleMap = getTitleMap();

		for (Map.Entry<Locale, String> entry : titleMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> defaultImageCopyrightMap =
			getDefaultImageCopyrightMap();

		for (Map.Entry<Locale, String> entry :
				defaultImageCopyrightMap.entrySet()) {

			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTitle();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			Campaign.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String title = getTitle(defaultLocale);

		if (Validator.isNull(title)) {
			setTitle(getTitle(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTitle(getTitle(defaultLocale), defaultLocale, defaultLocale);
		}

		String defaultImageCopyright = getDefaultImageCopyright(defaultLocale);

		if (Validator.isNull(defaultImageCopyright)) {
			setDefaultImageCopyright(
				getDefaultImageCopyright(modelDefaultLanguageId),
				defaultLocale);
		}
		else {
			setDefaultImageCopyright(
				getDefaultImageCopyright(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public Campaign toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Campaign>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CampaignImpl campaignImpl = new CampaignImpl();

		campaignImpl.setUuid(getUuid());
		campaignImpl.setCampaignId(getCampaignId());
		campaignImpl.setGroupId(getGroupId());
		campaignImpl.setCompanyId(getCompanyId());
		campaignImpl.setUserId(getUserId());
		campaignImpl.setUserName(getUserName());
		campaignImpl.setCreateDate(getCreateDate());
		campaignImpl.setModifiedDate(getModifiedDate());
		campaignImpl.setLastPublishDate(getLastPublishDate());
		campaignImpl.setStatus(getStatus());
		campaignImpl.setStatusByUserId(getStatusByUserId());
		campaignImpl.setStatusByUserName(getStatusByUserName());
		campaignImpl.setStatusDate(getStatusDate());
		campaignImpl.setTitle(getTitle());
		campaignImpl.setDefaultImageId(getDefaultImageId());
		campaignImpl.setDefaultImageCopyright(getDefaultImageCopyright());
		campaignImpl.setManagersIds(getManagersIds());
		campaignImpl.setExportEnabled(getExportEnabled());
		campaignImpl.setStartDate(getStartDate());
		campaignImpl.setEndDate(getEndDate());

		campaignImpl.resetOriginalValues();

		return campaignImpl;
	}

	@Override
	public int compareTo(Campaign campaign) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), campaign.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Campaign)) {
			return false;
		}

		Campaign campaign = (Campaign)object;

		long primaryKey = campaign.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CampaignModelImpl campaignModelImpl = this;

		campaignModelImpl._originalUuid = campaignModelImpl._uuid;

		campaignModelImpl._originalGroupId = campaignModelImpl._groupId;

		campaignModelImpl._setOriginalGroupId = false;

		campaignModelImpl._originalCompanyId = campaignModelImpl._companyId;

		campaignModelImpl._setOriginalCompanyId = false;

		campaignModelImpl._setModifiedDate = false;

		campaignModelImpl._originalTitle = campaignModelImpl._title;

		campaignModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Campaign> toCacheModel() {
		CampaignCacheModel campaignCacheModel = new CampaignCacheModel();

		campaignCacheModel.uuid = getUuid();

		String uuid = campaignCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			campaignCacheModel.uuid = null;
		}

		campaignCacheModel.campaignId = getCampaignId();

		campaignCacheModel.groupId = getGroupId();

		campaignCacheModel.companyId = getCompanyId();

		campaignCacheModel.userId = getUserId();

		campaignCacheModel.userName = getUserName();

		String userName = campaignCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			campaignCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			campaignCacheModel.createDate = createDate.getTime();
		}
		else {
			campaignCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			campaignCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			campaignCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			campaignCacheModel.lastPublishDate = lastPublishDate.getTime();
		}
		else {
			campaignCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		campaignCacheModel.status = getStatus();

		campaignCacheModel.statusByUserId = getStatusByUserId();

		campaignCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = campaignCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			campaignCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			campaignCacheModel.statusDate = statusDate.getTime();
		}
		else {
			campaignCacheModel.statusDate = Long.MIN_VALUE;
		}

		campaignCacheModel.title = getTitle();

		String title = campaignCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			campaignCacheModel.title = null;
		}

		campaignCacheModel.defaultImageId = getDefaultImageId();

		campaignCacheModel.defaultImageCopyright = getDefaultImageCopyright();

		String defaultImageCopyright = campaignCacheModel.defaultImageCopyright;

		if ((defaultImageCopyright != null) &&
			(defaultImageCopyright.length() == 0)) {

			campaignCacheModel.defaultImageCopyright = null;
		}

		campaignCacheModel.managersIds = getManagersIds();

		String managersIds = campaignCacheModel.managersIds;

		if ((managersIds != null) && (managersIds.length() == 0)) {
			campaignCacheModel.managersIds = null;
		}

		Boolean exportEnabled = getExportEnabled();

		if (exportEnabled != null) {
			campaignCacheModel.exportEnabled = exportEnabled;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			campaignCacheModel.startDate = startDate.getTime();
		}
		else {
			campaignCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			campaignCacheModel.endDate = endDate.getTime();
		}
		else {
			campaignCacheModel.endDate = Long.MIN_VALUE;
		}

		return campaignCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Campaign, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Campaign, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Campaign, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Campaign)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Campaign, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Campaign, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Campaign, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Campaign)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Campaign>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _campaignId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _lastPublishDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _title;
	private String _titleCurrentLanguageId;
	private String _originalTitle;
	private long _defaultImageId;
	private String _defaultImageCopyright;
	private String _defaultImageCopyrightCurrentLanguageId;
	private String _managersIds;
	private Boolean _exportEnabled;
	private Date _startDate;
	private Date _endDate;
	private long _columnBitmask;
	private Campaign _escapedModel;

}