/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.agenda.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import eu.strasbourg.service.agenda.model.CampaignEventStatus;
import eu.strasbourg.service.agenda.model.CampaignEventStatusModel;
import eu.strasbourg.service.agenda.model.CampaignEventStatusSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CampaignEventStatus service. Represents a row in the &quot;agenda_CampaignEventStatus&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CampaignEventStatusModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CampaignEventStatusImpl}.
 * </p>
 *
 * @author BenjaminBini
 * @see CampaignEventStatusImpl
 * @see CampaignEventStatus
 * @see CampaignEventStatusModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CampaignEventStatusModelImpl extends BaseModelImpl<CampaignEventStatus>
	implements CampaignEventStatusModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a campaign event status model instance should use the {@link CampaignEventStatus} interface instead.
	 */
	public static final String TABLE_NAME = "agenda_CampaignEventStatus";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "statusId", Types.BIGINT },
			{ "status", Types.INTEGER },
			{ "comment_", Types.CLOB },
			{ "deletionDenied", Types.BOOLEAN },
			{ "date_", Types.TIMESTAMP },
			{ "campaignEventId", Types.BIGINT },
			{ "previousStatusId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("comment_", Types.CLOB);
		TABLE_COLUMNS_MAP.put("deletionDenied", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("date_", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("campaignEventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("previousStatusId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table agenda_CampaignEventStatus (uuid_ VARCHAR(75) null,statusId LONG not null primary key,status INTEGER,comment_ TEXT null,deletionDenied BOOLEAN,date_ DATE null,campaignEventId LONG,previousStatusId LONG,userId LONG,userName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table agenda_CampaignEventStatus";
	public static final String ORDER_BY_JPQL = " ORDER BY campaignEventStatus.statusId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY agenda_CampaignEventStatus.statusId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(eu.strasbourg.service.agenda.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.eu.strasbourg.service.agenda.model.CampaignEventStatus"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(eu.strasbourg.service.agenda.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.eu.strasbourg.service.agenda.model.CampaignEventStatus"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(eu.strasbourg.service.agenda.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.eu.strasbourg.service.agenda.model.CampaignEventStatus"),
			true);
	public static final long CAMPAIGNEVENTID_COLUMN_BITMASK = 1L;
	public static final long UUID_COLUMN_BITMASK = 2L;
	public static final long STATUSID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CampaignEventStatus toModel(CampaignEventStatusSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CampaignEventStatus model = new CampaignEventStatusImpl();

		model.setUuid(soapModel.getUuid());
		model.setStatusId(soapModel.getStatusId());
		model.setStatus(soapModel.getStatus());
		model.setComment(soapModel.getComment());
		model.setDeletionDenied(soapModel.getDeletionDenied());
		model.setDate(soapModel.getDate());
		model.setCampaignEventId(soapModel.getCampaignEventId());
		model.setPreviousStatusId(soapModel.getPreviousStatusId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CampaignEventStatus> toModels(
		CampaignEventStatusSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CampaignEventStatus> models = new ArrayList<CampaignEventStatus>(soapModels.length);

		for (CampaignEventStatusSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(eu.strasbourg.service.agenda.service.util.PropsUtil.get(
				"lock.expiration.time.eu.strasbourg.service.agenda.model.CampaignEventStatus"));

	public CampaignEventStatusModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _statusId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStatusId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _statusId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CampaignEventStatus.class;
	}

	@Override
	public String getModelClassName() {
		return CampaignEventStatus.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("statusId", getStatusId());
		attributes.put("status", getStatus());
		attributes.put("comment", getComment());
		attributes.put("deletionDenied", getDeletionDenied());
		attributes.put("date", getDate());
		attributes.put("campaignEventId", getCampaignEventId());
		attributes.put("previousStatusId", getPreviousStatusId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long statusId = (Long)attributes.get("statusId");

		if (statusId != null) {
			setStatusId(statusId);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		String comment = (String)attributes.get("comment");

		if (comment != null) {
			setComment(comment);
		}

		Boolean deletionDenied = (Boolean)attributes.get("deletionDenied");

		if (deletionDenied != null) {
			setDeletionDenied(deletionDenied);
		}

		Date date = (Date)attributes.get("date");

		if (date != null) {
			setDate(date);
		}

		Long campaignEventId = (Long)attributes.get("campaignEventId");

		if (campaignEventId != null) {
			setCampaignEventId(campaignEventId);
		}

		Long previousStatusId = (Long)attributes.get("previousStatusId");

		if (previousStatusId != null) {
			setPreviousStatusId(previousStatusId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getStatusId() {
		return _statusId;
	}

	@Override
	public void setStatusId(long statusId) {
		_statusId = statusId;
	}

	@JSON
	@Override
	public Integer getStatus() {
		return _status;
	}

	@Override
	public void setStatus(Integer status) {
		_status = status;
	}

	@JSON
	@Override
	public String getComment() {
		if (_comment == null) {
			return StringPool.BLANK;
		}
		else {
			return _comment;
		}
	}

	@Override
	public void setComment(String comment) {
		_comment = comment;
	}

	@JSON
	@Override
	public Boolean getDeletionDenied() {
		return _deletionDenied;
	}

	@Override
	public void setDeletionDenied(Boolean deletionDenied) {
		_deletionDenied = deletionDenied;
	}

	@JSON
	@Override
	public Date getDate() {
		return _date;
	}

	@Override
	public void setDate(Date date) {
		_date = date;
	}

	@JSON
	@Override
	public long getCampaignEventId() {
		return _campaignEventId;
	}

	@Override
	public void setCampaignEventId(long campaignEventId) {
		_columnBitmask |= CAMPAIGNEVENTID_COLUMN_BITMASK;

		if (!_setOriginalCampaignEventId) {
			_setOriginalCampaignEventId = true;

			_originalCampaignEventId = _campaignEventId;
		}

		_campaignEventId = campaignEventId;
	}

	public long getOriginalCampaignEventId() {
		return _originalCampaignEventId;
	}

	@JSON
	@Override
	public long getPreviousStatusId() {
		return _previousStatusId;
	}

	@Override
	public void setPreviousStatusId(long previousStatusId) {
		_previousStatusId = previousStatusId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CampaignEventStatus.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CampaignEventStatus toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CampaignEventStatus)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CampaignEventStatusImpl campaignEventStatusImpl = new CampaignEventStatusImpl();

		campaignEventStatusImpl.setUuid(getUuid());
		campaignEventStatusImpl.setStatusId(getStatusId());
		campaignEventStatusImpl.setStatus(getStatus());
		campaignEventStatusImpl.setComment(getComment());
		campaignEventStatusImpl.setDeletionDenied(getDeletionDenied());
		campaignEventStatusImpl.setDate(getDate());
		campaignEventStatusImpl.setCampaignEventId(getCampaignEventId());
		campaignEventStatusImpl.setPreviousStatusId(getPreviousStatusId());
		campaignEventStatusImpl.setUserId(getUserId());
		campaignEventStatusImpl.setUserName(getUserName());

		campaignEventStatusImpl.resetOriginalValues();

		return campaignEventStatusImpl;
	}

	@Override
	public int compareTo(CampaignEventStatus campaignEventStatus) {
		long primaryKey = campaignEventStatus.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CampaignEventStatus)) {
			return false;
		}

		CampaignEventStatus campaignEventStatus = (CampaignEventStatus)obj;

		long primaryKey = campaignEventStatus.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CampaignEventStatusModelImpl campaignEventStatusModelImpl = this;

		campaignEventStatusModelImpl._originalUuid = campaignEventStatusModelImpl._uuid;

		campaignEventStatusModelImpl._originalCampaignEventId = campaignEventStatusModelImpl._campaignEventId;

		campaignEventStatusModelImpl._setOriginalCampaignEventId = false;

		campaignEventStatusModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CampaignEventStatus> toCacheModel() {
		CampaignEventStatusCacheModel campaignEventStatusCacheModel = new CampaignEventStatusCacheModel();

		campaignEventStatusCacheModel.uuid = getUuid();

		String uuid = campaignEventStatusCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			campaignEventStatusCacheModel.uuid = null;
		}

		campaignEventStatusCacheModel.statusId = getStatusId();

		campaignEventStatusCacheModel.status = getStatus();

		campaignEventStatusCacheModel.comment = getComment();

		String comment = campaignEventStatusCacheModel.comment;

		if ((comment != null) && (comment.length() == 0)) {
			campaignEventStatusCacheModel.comment = null;
		}

		campaignEventStatusCacheModel.deletionDenied = getDeletionDenied();

		Date date = getDate();

		if (date != null) {
			campaignEventStatusCacheModel.date = date.getTime();
		}
		else {
			campaignEventStatusCacheModel.date = Long.MIN_VALUE;
		}

		campaignEventStatusCacheModel.campaignEventId = getCampaignEventId();

		campaignEventStatusCacheModel.previousStatusId = getPreviousStatusId();

		campaignEventStatusCacheModel.userId = getUserId();

		campaignEventStatusCacheModel.userName = getUserName();

		String userName = campaignEventStatusCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			campaignEventStatusCacheModel.userName = null;
		}

		return campaignEventStatusCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", statusId=");
		sb.append(getStatusId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", comment=");
		sb.append(getComment());
		sb.append(", deletionDenied=");
		sb.append(getDeletionDenied());
		sb.append(", date=");
		sb.append(getDate());
		sb.append(", campaignEventId=");
		sb.append(getCampaignEventId());
		sb.append(", previousStatusId=");
		sb.append(getPreviousStatusId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("eu.strasbourg.service.agenda.model.CampaignEventStatus");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusId</column-name><column-value><![CDATA[");
		sb.append(getStatusId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>comment</column-name><column-value><![CDATA[");
		sb.append(getComment());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deletionDenied</column-name><column-value><![CDATA[");
		sb.append(getDeletionDenied());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>date</column-name><column-value><![CDATA[");
		sb.append(getDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>campaignEventId</column-name><column-value><![CDATA[");
		sb.append(getCampaignEventId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>previousStatusId</column-name><column-value><![CDATA[");
		sb.append(getPreviousStatusId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CampaignEventStatus.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CampaignEventStatus.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _statusId;
	private Integer _status;
	private String _comment;
	private Boolean _deletionDenied;
	private Date _date;
	private long _campaignEventId;
	private long _originalCampaignEventId;
	private boolean _setOriginalCampaignEventId;
	private long _previousStatusId;
	private long _userId;
	private String _userName;
	private long _columnBitmask;
	private CampaignEventStatus _escapedModel;
}