/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.agenda.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.kernel.util.Validator;

import eu.strasbourg.service.agenda.model.EventPeriod;
import eu.strasbourg.service.agenda.model.EventPeriodModel;
import eu.strasbourg.service.agenda.model.EventPeriodSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * The base model implementation for the EventPeriod service. Represents a row in the &quot;agenda_EventPeriod&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link EventPeriodModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EventPeriodImpl}.
 * </p>
 *
 * @author BenjaminBini
 * @see EventPeriodImpl
 * @see EventPeriod
 * @see EventPeriodModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class EventPeriodModelImpl extends BaseModelImpl<EventPeriod>
	implements EventPeriodModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a event period model instance should use the {@link EventPeriod} interface instead.
	 */
	public static final String TABLE_NAME = "agenda_EventPeriod";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "eventPeriodId", Types.BIGINT },
			{ "startDate", Types.TIMESTAMP },
			{ "endDate", Types.TIMESTAMP },
			{ "timeDetail", Types.VARCHAR },
			{ "eventId", Types.BIGINT },
			{ "campaignEventId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventPeriodId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("timeDetail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("campaignEventId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table agenda_EventPeriod (uuid_ VARCHAR(75) null,eventPeriodId LONG not null primary key,startDate DATE null,endDate DATE null,timeDetail STRING null,eventId LONG,campaignEventId LONG)";
	public static final String TABLE_SQL_DROP = "drop table agenda_EventPeriod";
	public static final String ORDER_BY_JPQL = " ORDER BY eventPeriod.eventPeriodId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY agenda_EventPeriod.eventPeriodId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(eu.strasbourg.service.agenda.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.eu.strasbourg.service.agenda.model.EventPeriod"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(eu.strasbourg.service.agenda.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.eu.strasbourg.service.agenda.model.EventPeriod"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(eu.strasbourg.service.agenda.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.eu.strasbourg.service.agenda.model.EventPeriod"),
			true);
	public static final long CAMPAIGNEVENTID_COLUMN_BITMASK = 1L;
	public static final long EVENTID_COLUMN_BITMASK = 2L;
	public static final long UUID_COLUMN_BITMASK = 4L;
	public static final long EVENTPERIODID_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EventPeriod toModel(EventPeriodSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EventPeriod model = new EventPeriodImpl();

		model.setUuid(soapModel.getUuid());
		model.setEventPeriodId(soapModel.getEventPeriodId());
		model.setStartDate(soapModel.getStartDate());
		model.setEndDate(soapModel.getEndDate());
		model.setTimeDetail(soapModel.getTimeDetail());
		model.setEventId(soapModel.getEventId());
		model.setCampaignEventId(soapModel.getCampaignEventId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EventPeriod> toModels(EventPeriodSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EventPeriod> models = new ArrayList<EventPeriod>(soapModels.length);

		for (EventPeriodSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(eu.strasbourg.service.agenda.service.util.PropsUtil.get(
				"lock.expiration.time.eu.strasbourg.service.agenda.model.EventPeriod"));

	public EventPeriodModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _eventPeriodId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEventPeriodId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _eventPeriodId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EventPeriod.class;
	}

	@Override
	public String getModelClassName() {
		return EventPeriod.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("eventPeriodId", getEventPeriodId());
		attributes.put("startDate", getStartDate());
		attributes.put("endDate", getEndDate());
		attributes.put("timeDetail", getTimeDetail());
		attributes.put("eventId", getEventId());
		attributes.put("campaignEventId", getCampaignEventId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long eventPeriodId = (Long)attributes.get("eventPeriodId");

		if (eventPeriodId != null) {
			setEventPeriodId(eventPeriodId);
		}

		Date startDate = (Date)attributes.get("startDate");

		if (startDate != null) {
			setStartDate(startDate);
		}

		Date endDate = (Date)attributes.get("endDate");

		if (endDate != null) {
			setEndDate(endDate);
		}

		String timeDetail = (String)attributes.get("timeDetail");

		if (timeDetail != null) {
			setTimeDetail(timeDetail);
		}

		Long eventId = (Long)attributes.get("eventId");

		if (eventId != null) {
			setEventId(eventId);
		}

		Long campaignEventId = (Long)attributes.get("campaignEventId");

		if (campaignEventId != null) {
			setCampaignEventId(campaignEventId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getEventPeriodId() {
		return _eventPeriodId;
	}

	@Override
	public void setEventPeriodId(long eventPeriodId) {
		_eventPeriodId = eventPeriodId;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		_endDate = endDate;
	}

	@JSON
	@Override
	public String getTimeDetail() {
		if (_timeDetail == null) {
			return StringPool.BLANK;
		}
		else {
			return _timeDetail;
		}
	}

	@Override
	public String getTimeDetail(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTimeDetail(languageId);
	}

	@Override
	public String getTimeDetail(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getTimeDetail(languageId, useDefault);
	}

	@Override
	public String getTimeDetail(String languageId) {
		return LocalizationUtil.getLocalization(getTimeDetail(), languageId);
	}

	@Override
	public String getTimeDetail(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(getTimeDetail(), languageId,
			useDefault);
	}

	@Override
	public String getTimeDetailCurrentLanguageId() {
		return _timeDetailCurrentLanguageId;
	}

	@JSON
	@Override
	public String getTimeDetailCurrentValue() {
		Locale locale = getLocale(_timeDetailCurrentLanguageId);

		return getTimeDetail(locale);
	}

	@Override
	public Map<Locale, String> getTimeDetailMap() {
		return LocalizationUtil.getLocalizationMap(getTimeDetail());
	}

	@Override
	public void setTimeDetail(String timeDetail) {
		_timeDetail = timeDetail;
	}

	@Override
	public void setTimeDetail(String timeDetail, Locale locale) {
		setTimeDetail(timeDetail, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setTimeDetail(String timeDetail, Locale locale,
		Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(timeDetail)) {
			setTimeDetail(LocalizationUtil.updateLocalization(getTimeDetail(),
					"TimeDetail", timeDetail, languageId, defaultLanguageId));
		}
		else {
			setTimeDetail(LocalizationUtil.removeLocalization(getTimeDetail(),
					"TimeDetail", languageId));
		}
	}

	@Override
	public void setTimeDetailCurrentLanguageId(String languageId) {
		_timeDetailCurrentLanguageId = languageId;
	}

	@Override
	public void setTimeDetailMap(Map<Locale, String> timeDetailMap) {
		setTimeDetailMap(timeDetailMap, LocaleUtil.getDefault());
	}

	@Override
	public void setTimeDetailMap(Map<Locale, String> timeDetailMap,
		Locale defaultLocale) {
		if (timeDetailMap == null) {
			return;
		}

		setTimeDetail(LocalizationUtil.updateLocalization(timeDetailMap,
				getTimeDetail(), "TimeDetail",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public long getEventId() {
		return _eventId;
	}

	@Override
	public void setEventId(long eventId) {
		_columnBitmask |= EVENTID_COLUMN_BITMASK;

		if (!_setOriginalEventId) {
			_setOriginalEventId = true;

			_originalEventId = _eventId;
		}

		_eventId = eventId;
	}

	public long getOriginalEventId() {
		return _originalEventId;
	}

	@JSON
	@Override
	public long getCampaignEventId() {
		return _campaignEventId;
	}

	@Override
	public void setCampaignEventId(long campaignEventId) {
		_columnBitmask |= CAMPAIGNEVENTID_COLUMN_BITMASK;

		if (!_setOriginalCampaignEventId) {
			_setOriginalCampaignEventId = true;

			_originalCampaignEventId = _campaignEventId;
		}

		_campaignEventId = campaignEventId;
	}

	public long getOriginalCampaignEventId() {
		return _originalCampaignEventId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			EventPeriod.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> timeDetailMap = getTimeDetailMap();

		for (Map.Entry<Locale, String> entry : timeDetailMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getTimeDetail();

		if (xml == null) {
			return StringPool.BLANK;
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(EventPeriod.class.getName(),
				getPrimaryKey(), defaultLocale, availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {
		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String timeDetail = getTimeDetail(defaultLocale);

		if (Validator.isNull(timeDetail)) {
			setTimeDetail(getTimeDetail(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setTimeDetail(getTimeDetail(defaultLocale), defaultLocale,
				defaultLocale);
		}
	}

	@Override
	public EventPeriod toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EventPeriod)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EventPeriodImpl eventPeriodImpl = new EventPeriodImpl();

		eventPeriodImpl.setUuid(getUuid());
		eventPeriodImpl.setEventPeriodId(getEventPeriodId());
		eventPeriodImpl.setStartDate(getStartDate());
		eventPeriodImpl.setEndDate(getEndDate());
		eventPeriodImpl.setTimeDetail(getTimeDetail());
		eventPeriodImpl.setEventId(getEventId());
		eventPeriodImpl.setCampaignEventId(getCampaignEventId());

		eventPeriodImpl.resetOriginalValues();

		return eventPeriodImpl;
	}

	@Override
	public int compareTo(EventPeriod eventPeriod) {
		long primaryKey = eventPeriod.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EventPeriod)) {
			return false;
		}

		EventPeriod eventPeriod = (EventPeriod)obj;

		long primaryKey = eventPeriod.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		EventPeriodModelImpl eventPeriodModelImpl = this;

		eventPeriodModelImpl._originalUuid = eventPeriodModelImpl._uuid;

		eventPeriodModelImpl._originalEventId = eventPeriodModelImpl._eventId;

		eventPeriodModelImpl._setOriginalEventId = false;

		eventPeriodModelImpl._originalCampaignEventId = eventPeriodModelImpl._campaignEventId;

		eventPeriodModelImpl._setOriginalCampaignEventId = false;

		eventPeriodModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EventPeriod> toCacheModel() {
		EventPeriodCacheModel eventPeriodCacheModel = new EventPeriodCacheModel();

		eventPeriodCacheModel.uuid = getUuid();

		String uuid = eventPeriodCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			eventPeriodCacheModel.uuid = null;
		}

		eventPeriodCacheModel.eventPeriodId = getEventPeriodId();

		Date startDate = getStartDate();

		if (startDate != null) {
			eventPeriodCacheModel.startDate = startDate.getTime();
		}
		else {
			eventPeriodCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			eventPeriodCacheModel.endDate = endDate.getTime();
		}
		else {
			eventPeriodCacheModel.endDate = Long.MIN_VALUE;
		}

		eventPeriodCacheModel.timeDetail = getTimeDetail();

		String timeDetail = eventPeriodCacheModel.timeDetail;

		if ((timeDetail != null) && (timeDetail.length() == 0)) {
			eventPeriodCacheModel.timeDetail = null;
		}

		eventPeriodCacheModel.eventId = getEventId();

		eventPeriodCacheModel.campaignEventId = getCampaignEventId();

		return eventPeriodCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", eventPeriodId=");
		sb.append(getEventPeriodId());
		sb.append(", startDate=");
		sb.append(getStartDate());
		sb.append(", endDate=");
		sb.append(getEndDate());
		sb.append(", timeDetail=");
		sb.append(getTimeDetail());
		sb.append(", eventId=");
		sb.append(getEventId());
		sb.append(", campaignEventId=");
		sb.append(getCampaignEventId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("eu.strasbourg.service.agenda.model.EventPeriod");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eventPeriodId</column-name><column-value><![CDATA[");
		sb.append(getEventPeriodId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startDate</column-name><column-value><![CDATA[");
		sb.append(getStartDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endDate</column-name><column-value><![CDATA[");
		sb.append(getEndDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>timeDetail</column-name><column-value><![CDATA[");
		sb.append(getTimeDetail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eventId</column-name><column-value><![CDATA[");
		sb.append(getEventId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>campaignEventId</column-name><column-value><![CDATA[");
		sb.append(getCampaignEventId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = EventPeriod.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			EventPeriod.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _eventPeriodId;
	private Date _startDate;
	private Date _endDate;
	private String _timeDetail;
	private String _timeDetailCurrentLanguageId;
	private long _eventId;
	private long _originalEventId;
	private boolean _setOriginalEventId;
	private long _campaignEventId;
	private long _originalCampaignEventId;
	private boolean _setOriginalCampaignEventId;
	private long _columnBitmask;
	private EventPeriod _escapedModel;
}