/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.notif.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.Validator;

import eu.strasbourg.service.notif.model.NatureNotif;
import eu.strasbourg.service.notif.model.NatureNotifModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NatureNotif service. Represents a row in the &quot;notif_NatureNotif&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>NatureNotifModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NatureNotifImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NatureNotifImpl
 * @generated
 */
@ProviderType
public class NatureNotifModelImpl
	extends BaseModelImpl<NatureNotif> implements NatureNotifModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a nature notif model instance should use the <code>NatureNotif</code> interface instead.
	 */
	public static final String TABLE_NAME = "notif_NatureNotif";

	public static final Object[][] TABLE_COLUMNS = {
		{"natureId", Types.BIGINT}, {"serviceId", Types.BIGINT},
		{"name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("natureId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("serviceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table notif_NatureNotif (natureId LONG not null primary key,serviceId LONG,name STRING null)";

	public static final String TABLE_SQL_DROP = "drop table notif_NatureNotif";

	public static final String ORDER_BY_JPQL =
		" ORDER BY natureNotif.natureId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY notif_NatureNotif.natureId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.notif.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.eu.strasbourg.service.notif.model.NatureNotif"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.notif.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.eu.strasbourg.service.notif.model.NatureNotif"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		eu.strasbourg.service.notif.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.eu.strasbourg.service.notif.model.NatureNotif"),
		true);

	public static final long SERVICEID_COLUMN_BITMASK = 1L;

	public static final long NATUREID_COLUMN_BITMASK = 2L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		eu.strasbourg.service.notif.service.util.ServiceProps.get(
			"lock.expiration.time.eu.strasbourg.service.notif.model.NatureNotif"));

	public NatureNotifModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _natureId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNatureId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _natureId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NatureNotif.class;
	}

	@Override
	public String getModelClassName() {
		return NatureNotif.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NatureNotif, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NatureNotif, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NatureNotif, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((NatureNotif)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NatureNotif, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NatureNotif, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NatureNotif)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NatureNotif, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NatureNotif, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, NatureNotif>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			NatureNotif.class.getClassLoader(), NatureNotif.class,
			ModelWrapper.class);

		try {
			Constructor<NatureNotif> constructor =
				(Constructor<NatureNotif>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<NatureNotif, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<NatureNotif, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<NatureNotif, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<NatureNotif, Object>>();
		Map<String, BiConsumer<NatureNotif, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<NatureNotif, ?>>();

		attributeGetterFunctions.put(
			"natureId",
			new Function<NatureNotif, Object>() {

				@Override
				public Object apply(NatureNotif natureNotif) {
					return natureNotif.getNatureId();
				}

			});
		attributeSetterBiConsumers.put(
			"natureId",
			new BiConsumer<NatureNotif, Object>() {

				@Override
				public void accept(NatureNotif natureNotif, Object natureId) {
					natureNotif.setNatureId((Long)natureId);
				}

			});
		attributeGetterFunctions.put(
			"serviceId",
			new Function<NatureNotif, Object>() {

				@Override
				public Object apply(NatureNotif natureNotif) {
					return natureNotif.getServiceId();
				}

			});
		attributeSetterBiConsumers.put(
			"serviceId",
			new BiConsumer<NatureNotif, Object>() {

				@Override
				public void accept(NatureNotif natureNotif, Object serviceId) {
					natureNotif.setServiceId((Long)serviceId);
				}

			});
		attributeGetterFunctions.put(
			"name",
			new Function<NatureNotif, Object>() {

				@Override
				public Object apply(NatureNotif natureNotif) {
					return natureNotif.getName();
				}

			});
		attributeSetterBiConsumers.put(
			"name",
			new BiConsumer<NatureNotif, Object>() {

				@Override
				public void accept(NatureNotif natureNotif, Object name) {
					natureNotif.setName((String)name);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getNatureId() {
		return _natureId;
	}

	@Override
	public void setNatureId(long natureId) {
		_natureId = natureId;
	}

	@Override
	public long getServiceId() {
		return _serviceId;
	}

	@Override
	public void setServiceId(long serviceId) {
		_columnBitmask |= SERVICEID_COLUMN_BITMASK;

		if (!_setOriginalServiceId) {
			_setOriginalServiceId = true;

			_originalServiceId = _serviceId;
		}

		_serviceId = serviceId;
	}

	public long getOriginalServiceId() {
		return _originalServiceId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	@Override
	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	@Override
	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getName(), languageId, useDefault);
	}

	@Override
	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	@Override
	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getDefault());
	}

	@Override
	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(
				LocalizationUtil.updateLocalization(
					getName(), "Name", name, languageId, defaultLanguageId));
		}
		else {
			setName(
				LocalizationUtil.removeLocalization(
					getName(), "Name", languageId));
		}
	}

	@Override
	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getDefault());
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		setName(
			LocalizationUtil.updateLocalization(
				nameMap, getName(), "Name",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, NatureNotif.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> nameMap = getNameMap();

		for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			NatureNotif.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String name = getName(defaultLocale);

		if (Validator.isNull(name)) {
			setName(getName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setName(getName(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public NatureNotif toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NatureNotifImpl natureNotifImpl = new NatureNotifImpl();

		natureNotifImpl.setNatureId(getNatureId());
		natureNotifImpl.setServiceId(getServiceId());
		natureNotifImpl.setName(getName());

		natureNotifImpl.resetOriginalValues();

		return natureNotifImpl;
	}

	@Override
	public int compareTo(NatureNotif natureNotif) {
		long primaryKey = natureNotif.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof NatureNotif)) {
			return false;
		}

		NatureNotif natureNotif = (NatureNotif)obj;

		long primaryKey = natureNotif.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		NatureNotifModelImpl natureNotifModelImpl = this;

		natureNotifModelImpl._originalServiceId =
			natureNotifModelImpl._serviceId;

		natureNotifModelImpl._setOriginalServiceId = false;

		natureNotifModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<NatureNotif> toCacheModel() {
		NatureNotifCacheModel natureNotifCacheModel =
			new NatureNotifCacheModel();

		natureNotifCacheModel.natureId = getNatureId();

		natureNotifCacheModel.serviceId = getServiceId();

		natureNotifCacheModel.name = getName();

		String name = natureNotifCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			natureNotifCacheModel.name = null;
		}

		return natureNotifCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NatureNotif, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NatureNotif, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NatureNotif, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((NatureNotif)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<NatureNotif, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<NatureNotif, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NatureNotif, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((NatureNotif)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, NatureNotif>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private long _natureId;
	private long _serviceId;
	private long _originalServiceId;
	private boolean _setOriginalServiceId;
	private String _name;
	private String _nameCurrentLanguageId;
	private long _columnBitmask;
	private NatureNotif _escapedModel;

}