/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.video.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedGroupedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the VideoGallery service. Represents a row in the &quot;video_VideoGallery&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link eu.strasbourg.service.video.model.impl.VideoGalleryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link eu.strasbourg.service.video.model.impl.VideoGalleryImpl}.
 * </p>
 *
 * @author BenjaminBini
 * @see VideoGallery
 * @see eu.strasbourg.service.video.model.impl.VideoGalleryImpl
 * @see eu.strasbourg.service.video.model.impl.VideoGalleryModelImpl
 * @generated
 */
@ProviderType
public interface VideoGalleryModel extends BaseModel<VideoGallery>,
	LocalizedModel, ShardedModel, StagedGroupedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a video gallery model instance should use the {@link VideoGallery} interface instead.
	 */

	/**
	 * Returns the primary key of this video gallery.
	 *
	 * @return the primary key of this video gallery
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this video gallery.
	 *
	 * @param primaryKey the primary key of this video gallery
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this video gallery.
	 *
	 * @return the uuid of this video gallery
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this video gallery.
	 *
	 * @param uuid the uuid of this video gallery
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the gallery ID of this video gallery.
	 *
	 * @return the gallery ID of this video gallery
	 */
	public long getGalleryId();

	/**
	 * Sets the gallery ID of this video gallery.
	 *
	 * @param galleryId the gallery ID of this video gallery
	 */
	public void setGalleryId(long galleryId);

	/**
	 * Returns the group ID of this video gallery.
	 *
	 * @return the group ID of this video gallery
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this video gallery.
	 *
	 * @param groupId the group ID of this video gallery
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this video gallery.
	 *
	 * @return the company ID of this video gallery
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this video gallery.
	 *
	 * @param companyId the company ID of this video gallery
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this video gallery.
	 *
	 * @return the user ID of this video gallery
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this video gallery.
	 *
	 * @param userId the user ID of this video gallery
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this video gallery.
	 *
	 * @return the user uuid of this video gallery
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this video gallery.
	 *
	 * @param userUuid the user uuid of this video gallery
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this video gallery.
	 *
	 * @return the user name of this video gallery
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this video gallery.
	 *
	 * @param userName the user name of this video gallery
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this video gallery.
	 *
	 * @return the create date of this video gallery
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this video gallery.
	 *
	 * @param createDate the create date of this video gallery
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this video gallery.
	 *
	 * @return the modified date of this video gallery
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this video gallery.
	 *
	 * @param modifiedDate the modified date of this video gallery
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the last publish date of this video gallery.
	 *
	 * @return the last publish date of this video gallery
	 */
	@Override
	public Date getLastPublishDate();

	/**
	 * Sets the last publish date of this video gallery.
	 *
	 * @param lastPublishDate the last publish date of this video gallery
	 */
	@Override
	public void setLastPublishDate(Date lastPublishDate);

	/**
	 * Returns the status of this video gallery.
	 *
	 * @return the status of this video gallery
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this video gallery.
	 *
	 * @param status the status of this video gallery
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this video gallery.
	 *
	 * @return the status by user ID of this video gallery
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this video gallery.
	 *
	 * @param statusByUserId the status by user ID of this video gallery
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this video gallery.
	 *
	 * @return the status by user uuid of this video gallery
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this video gallery.
	 *
	 * @param statusByUserUuid the status by user uuid of this video gallery
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this video gallery.
	 *
	 * @return the status by user name of this video gallery
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this video gallery.
	 *
	 * @param statusByUserName the status by user name of this video gallery
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this video gallery.
	 *
	 * @return the status date of this video gallery
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this video gallery.
	 *
	 * @param statusDate the status date of this video gallery
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the title of this video gallery.
	 *
	 * @return the title of this video gallery
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this video gallery in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this video gallery
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this video gallery in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this video gallery. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this video gallery in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this video gallery
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this video gallery in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this video gallery
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this video gallery.
	 *
	 * @return the locales and localized titles of this video gallery
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this video gallery.
	 *
	 * @param title the title of this video gallery
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this video gallery in the language.
	 *
	 * @param title the localized title of this video gallery
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this video gallery in the language, and sets the default locale.
	 *
	 * @param title the localized title of this video gallery
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this video gallery from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this video gallery
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this video gallery from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this video gallery
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	/**
	 * Returns the description of this video gallery.
	 *
	 * @return the description of this video gallery
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this video gallery in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this video gallery
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this video gallery in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this video gallery. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this video gallery in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this video gallery
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this video gallery in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this video gallery
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this video gallery.
	 *
	 * @return the locales and localized descriptions of this video gallery
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this video gallery.
	 *
	 * @param description the description of this video gallery
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this video gallery in the language.
	 *
	 * @param description the localized description of this video gallery
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this video gallery in the language, and sets the default locale.
	 *
	 * @param description the localized description of this video gallery
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this video gallery from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this video gallery
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this video gallery from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this video gallery
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the publication date of this video gallery.
	 *
	 * @return the publication date of this video gallery
	 */
	public Date getPublicationDate();

	/**
	 * Sets the publication date of this video gallery.
	 *
	 * @param publicationDate the publication date of this video gallery
	 */
	public void setPublicationDate(Date publicationDate);

	/**
	 * Returns the image ID of this video gallery.
	 *
	 * @return the image ID of this video gallery
	 */
	public Long getImageId();

	/**
	 * Sets the image ID of this video gallery.
	 *
	 * @param imageId the image ID of this video gallery
	 */
	public void setImageId(Long imageId);

	/**
	 * Returns <code>true</code> if this video gallery is approved.
	 *
	 * @return <code>true</code> if this video gallery is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this video gallery is denied.
	 *
	 * @return <code>true</code> if this video gallery is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this video gallery is a draft.
	 *
	 * @return <code>true</code> if this video gallery is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this video gallery is expired.
	 *
	 * @return <code>true</code> if this video gallery is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this video gallery is inactive.
	 *
	 * @return <code>true</code> if this video gallery is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this video gallery is incomplete.
	 *
	 * @return <code>true</code> if this video gallery is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this video gallery is pending.
	 *
	 * @return <code>true</code> if this video gallery is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this video gallery is scheduled.
	 *
	 * @return <code>true</code> if this video gallery is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(
		eu.strasbourg.service.video.model.VideoGallery videoGallery);

	@Override
	public int hashCode();

	@Override
	public CacheModel<eu.strasbourg.service.video.model.VideoGallery> toCacheModel();

	@Override
	public eu.strasbourg.service.video.model.VideoGallery toEscapedModel();

	@Override
	public eu.strasbourg.service.video.model.VideoGallery toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}