/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.help.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the HelpProposal service. Represents a row in the &quot;help_HelpProposal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>eu.strasbourg.service.help.model.impl.HelpProposalModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>eu.strasbourg.service.help.model.impl.HelpProposalImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HelpProposal
 * @generated
 */
@ProviderType
public interface HelpProposalModel
	extends BaseModel<HelpProposal>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a help proposal model instance should use the {@link HelpProposal} interface instead.
	 */

	/**
	 * Returns the primary key of this help proposal.
	 *
	 * @return the primary key of this help proposal
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this help proposal.
	 *
	 * @param primaryKey the primary key of this help proposal
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this help proposal.
	 *
	 * @return the uuid of this help proposal
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this help proposal.
	 *
	 * @param uuid the uuid of this help proposal
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the help proposal ID of this help proposal.
	 *
	 * @return the help proposal ID of this help proposal
	 */
	public long getHelpProposalId();

	/**
	 * Sets the help proposal ID of this help proposal.
	 *
	 * @param helpProposalId the help proposal ID of this help proposal
	 */
	public void setHelpProposalId(long helpProposalId);

	/**
	 * Returns the group ID of this help proposal.
	 *
	 * @return the group ID of this help proposal
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this help proposal.
	 *
	 * @param groupId the group ID of this help proposal
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this help proposal.
	 *
	 * @return the company ID of this help proposal
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this help proposal.
	 *
	 * @param companyId the company ID of this help proposal
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this help proposal.
	 *
	 * @return the user ID of this help proposal
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this help proposal.
	 *
	 * @param userId the user ID of this help proposal
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this help proposal.
	 *
	 * @return the user uuid of this help proposal
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this help proposal.
	 *
	 * @param userUuid the user uuid of this help proposal
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this help proposal.
	 *
	 * @return the user name of this help proposal
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this help proposal.
	 *
	 * @param userName the user name of this help proposal
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this help proposal.
	 *
	 * @return the create date of this help proposal
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this help proposal.
	 *
	 * @param createDate the create date of this help proposal
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this help proposal.
	 *
	 * @return the modified date of this help proposal
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this help proposal.
	 *
	 * @param modifiedDate the modified date of this help proposal
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this help proposal.
	 *
	 * @return the status of this help proposal
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this help proposal.
	 *
	 * @param status the status of this help proposal
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this help proposal.
	 *
	 * @return the status by user ID of this help proposal
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this help proposal.
	 *
	 * @param statusByUserId the status by user ID of this help proposal
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this help proposal.
	 *
	 * @return the status by user uuid of this help proposal
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this help proposal.
	 *
	 * @param statusByUserUuid the status by user uuid of this help proposal
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this help proposal.
	 *
	 * @return the status by user name of this help proposal
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this help proposal.
	 *
	 * @param statusByUserName the status by user name of this help proposal
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this help proposal.
	 *
	 * @return the status date of this help proposal
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this help proposal.
	 *
	 * @param statusDate the status date of this help proposal
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the title of this help proposal.
	 *
	 * @return the title of this help proposal
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this help proposal.
	 *
	 * @param title the title of this help proposal
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this help proposal.
	 *
	 * @return the description of this help proposal
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this help proposal.
	 *
	 * @param description the description of this help proposal
	 */
	public void setDescription(String description);

	/**
	 * Returns the in the name of of this help proposal.
	 *
	 * @return the in the name of of this help proposal
	 */
	@AutoEscape
	public String getInTheNameOf();

	/**
	 * Sets the in the name of of this help proposal.
	 *
	 * @param inTheNameOf the in the name of of this help proposal
	 */
	public void setInTheNameOf(String inTheNameOf);

	/**
	 * Returns the address of this help proposal.
	 *
	 * @return the address of this help proposal
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this help proposal.
	 *
	 * @param address the address of this help proposal
	 */
	public void setAddress(String address);

	/**
	 * Returns the city of this help proposal.
	 *
	 * @return the city of this help proposal
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this help proposal.
	 *
	 * @param city the city of this help proposal
	 */
	public void setCity(String city);

	/**
	 * Returns the postal code of this help proposal.
	 *
	 * @return the postal code of this help proposal
	 */
	public long getPostalCode();

	/**
	 * Sets the postal code of this help proposal.
	 *
	 * @param postalCode the postal code of this help proposal
	 */
	public void setPostalCode(long postalCode);

	/**
	 * Returns the modified by user date of this help proposal.
	 *
	 * @return the modified by user date of this help proposal
	 */
	public Date getModifiedByUserDate();

	/**
	 * Sets the modified by user date of this help proposal.
	 *
	 * @param modifiedByUserDate the modified by user date of this help proposal
	 */
	public void setModifiedByUserDate(Date modifiedByUserDate);

	/**
	 * Returns the spoken languages of this help proposal.
	 *
	 * @return the spoken languages of this help proposal
	 */
	@AutoEscape
	public String getSpokenLanguages();

	/**
	 * Sets the spoken languages of this help proposal.
	 *
	 * @param spokenLanguages the spoken languages of this help proposal
	 */
	public void setSpokenLanguages(String spokenLanguages);

	/**
	 * Returns the image ID of this help proposal.
	 *
	 * @return the image ID of this help proposal
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this help proposal.
	 *
	 * @param imageId the image ID of this help proposal
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the publik ID of this help proposal.
	 *
	 * @return the publik ID of this help proposal
	 */
	@AutoEscape
	public String getPublikId();

	/**
	 * Sets the publik ID of this help proposal.
	 *
	 * @param publikId the publik ID of this help proposal
	 */
	public void setPublikId(String publikId);

	/**
	 * Returns the publication date of this help proposal.
	 *
	 * @return the publication date of this help proposal
	 */
	public Date getPublicationDate();

	/**
	 * Sets the publication date of this help proposal.
	 *
	 * @param publicationDate the publication date of this help proposal
	 */
	public void setPublicationDate(Date publicationDate);

	/**
	 * Returns <code>true</code> if this help proposal is approved.
	 *
	 * @return <code>true</code> if this help proposal is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this help proposal is denied.
	 *
	 * @return <code>true</code> if this help proposal is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this help proposal is a draft.
	 *
	 * @return <code>true</code> if this help proposal is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this help proposal is expired.
	 *
	 * @return <code>true</code> if this help proposal is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this help proposal is inactive.
	 *
	 * @return <code>true</code> if this help proposal is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this help proposal is incomplete.
	 *
	 * @return <code>true</code> if this help proposal is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this help proposal is pending.
	 *
	 * @return <code>true</code> if this help proposal is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this help proposal is scheduled.
	 *
	 * @return <code>true</code> if this help proposal is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}