create table help_HelpProposal (
	uuid_ VARCHAR(75) null,
	helpProposalId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	title VARCHAR(400) null,
	description TEXT null,
	inTheNameOf VARCHAR(400) null,
	address VARCHAR(400) null,
	city VARCHAR(400) null,
	postalCode LONG,
	modifiedByUserDate DATE null,
	spokenLanguages VARCHAR(75) null,
	imageId LONG,
	publikId VARCHAR(75) null,
	publicationDate DATE null
);

create table help_HelpRequest (
	uuid_ VARCHAR(75) null,
	helpRequestId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	publikId VARCHAR(75) null,
	helpProposalId LONG,
	phoneNumber VARCHAR(75) null,
	message TEXT null,
	foodAllergies VARCHAR(400) null,
	studentCardImageId LONG
);