create table help_HelpProposal (
	uuid_ VARCHAR(75) null,
	helpProposalId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	title STRING null,
	description TEXT null,
	inTheNameOf VARCHAR(400) null,
	address VARCHAR(400) null,
	city VARCHAR(400) null,
	postalCode LONG,
	phoneNumber VARCHAR(75) null,
	modifiedByUserDate DATE null,
	spokenLanguages STRING null,
	agreementSigned1 BOOLEAN,
	agreementSigned2 BOOLEAN,
	agreementSigned3 BOOLEAN,
	imageId LONG,
	publikId VARCHAR(75) null,
	comment_ TEXT null
);

create table help_HelpRequest (
	uuid_ VARCHAR(75) null,
	helpRequestId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	publikId VARCHAR(75) null,
	helpProposalId LONG,
	phoneNumber VARCHAR(75) null,
	message TEXT null,
	studentCardImageId LONG
);