/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.formSendRecordField.service.base;

import com.liferay.asset.kernel.service.persistence.AssetEntryPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import eu.strasbourg.service.formSendRecordField.model.FormSendRecordField;
import eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldService;
import eu.strasbourg.service.formSendRecordField.service.persistence.FormSendRecordFieldPersistence;
import eu.strasbourg.service.formSendRecordField.service.persistence.FormSendRecordFieldSignalementPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the form send record field remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link eu.strasbourg.service.formSendRecordField.service.impl.FormSendRecordFieldServiceImpl}.
 * </p>
 *
 * @author Angélique Zunino
 * @see eu.strasbourg.service.formSendRecordField.service.impl.FormSendRecordFieldServiceImpl
 * @see eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldServiceUtil
 * @generated
 */
public abstract class FormSendRecordFieldServiceBaseImpl extends BaseServiceImpl
	implements FormSendRecordFieldService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldServiceUtil} to access the form send record field remote service.
	 */

	/**
	 * Returns the form send record field local service.
	 *
	 * @return the form send record field local service
	 */
	public eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldLocalService getFormSendRecordFieldLocalService() {
		return formSendRecordFieldLocalService;
	}

	/**
	 * Sets the form send record field local service.
	 *
	 * @param formSendRecordFieldLocalService the form send record field local service
	 */
	public void setFormSendRecordFieldLocalService(
		eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldLocalService formSendRecordFieldLocalService) {
		this.formSendRecordFieldLocalService = formSendRecordFieldLocalService;
	}

	/**
	 * Returns the form send record field remote service.
	 *
	 * @return the form send record field remote service
	 */
	public FormSendRecordFieldService getFormSendRecordFieldService() {
		return formSendRecordFieldService;
	}

	/**
	 * Sets the form send record field remote service.
	 *
	 * @param formSendRecordFieldService the form send record field remote service
	 */
	public void setFormSendRecordFieldService(
		FormSendRecordFieldService formSendRecordFieldService) {
		this.formSendRecordFieldService = formSendRecordFieldService;
	}

	/**
	 * Returns the form send record field persistence.
	 *
	 * @return the form send record field persistence
	 */
	public FormSendRecordFieldPersistence getFormSendRecordFieldPersistence() {
		return formSendRecordFieldPersistence;
	}

	/**
	 * Sets the form send record field persistence.
	 *
	 * @param formSendRecordFieldPersistence the form send record field persistence
	 */
	public void setFormSendRecordFieldPersistence(
		FormSendRecordFieldPersistence formSendRecordFieldPersistence) {
		this.formSendRecordFieldPersistence = formSendRecordFieldPersistence;
	}

	/**
	 * Returns the form send record field signalement local service.
	 *
	 * @return the form send record field signalement local service
	 */
	public eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldSignalementLocalService getFormSendRecordFieldSignalementLocalService() {
		return formSendRecordFieldSignalementLocalService;
	}

	/**
	 * Sets the form send record field signalement local service.
	 *
	 * @param formSendRecordFieldSignalementLocalService the form send record field signalement local service
	 */
	public void setFormSendRecordFieldSignalementLocalService(
		eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldSignalementLocalService formSendRecordFieldSignalementLocalService) {
		this.formSendRecordFieldSignalementLocalService = formSendRecordFieldSignalementLocalService;
	}

	/**
	 * Returns the form send record field signalement remote service.
	 *
	 * @return the form send record field signalement remote service
	 */
	public eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldSignalementService getFormSendRecordFieldSignalementService() {
		return formSendRecordFieldSignalementService;
	}

	/**
	 * Sets the form send record field signalement remote service.
	 *
	 * @param formSendRecordFieldSignalementService the form send record field signalement remote service
	 */
	public void setFormSendRecordFieldSignalementService(
		eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldSignalementService formSendRecordFieldSignalementService) {
		this.formSendRecordFieldSignalementService = formSendRecordFieldSignalementService;
	}

	/**
	 * Returns the form send record field signalement persistence.
	 *
	 * @return the form send record field signalement persistence
	 */
	public FormSendRecordFieldSignalementPersistence getFormSendRecordFieldSignalementPersistence() {
		return formSendRecordFieldSignalementPersistence;
	}

	/**
	 * Sets the form send record field signalement persistence.
	 *
	 * @param formSendRecordFieldSignalementPersistence the form send record field signalement persistence
	 */
	public void setFormSendRecordFieldSignalementPersistence(
		FormSendRecordFieldSignalementPersistence formSendRecordFieldSignalementPersistence) {
		this.formSendRecordFieldSignalementPersistence = formSendRecordFieldSignalementPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Returns the asset entry local service.
	 *
	 * @return the asset entry local service
	 */
	public com.liferay.asset.kernel.service.AssetEntryLocalService getAssetEntryLocalService() {
		return assetEntryLocalService;
	}

	/**
	 * Sets the asset entry local service.
	 *
	 * @param assetEntryLocalService the asset entry local service
	 */
	public void setAssetEntryLocalService(
		com.liferay.asset.kernel.service.AssetEntryLocalService assetEntryLocalService) {
		this.assetEntryLocalService = assetEntryLocalService;
	}

	/**
	 * Returns the asset entry remote service.
	 *
	 * @return the asset entry remote service
	 */
	public com.liferay.asset.kernel.service.AssetEntryService getAssetEntryService() {
		return assetEntryService;
	}

	/**
	 * Sets the asset entry remote service.
	 *
	 * @param assetEntryService the asset entry remote service
	 */
	public void setAssetEntryService(
		com.liferay.asset.kernel.service.AssetEntryService assetEntryService) {
		this.assetEntryService = assetEntryService;
	}

	/**
	 * Returns the asset entry persistence.
	 *
	 * @return the asset entry persistence
	 */
	public AssetEntryPersistence getAssetEntryPersistence() {
		return assetEntryPersistence;
	}

	/**
	 * Sets the asset entry persistence.
	 *
	 * @param assetEntryPersistence the asset entry persistence
	 */
	public void setAssetEntryPersistence(
		AssetEntryPersistence assetEntryPersistence) {
		this.assetEntryPersistence = assetEntryPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FormSendRecordFieldService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FormSendRecordField.class;
	}

	protected String getModelClassName() {
		return FormSendRecordField.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = formSendRecordFieldPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldLocalService.class)
	protected eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldLocalService formSendRecordFieldLocalService;
	@BeanReference(type = FormSendRecordFieldService.class)
	protected FormSendRecordFieldService formSendRecordFieldService;
	@BeanReference(type = FormSendRecordFieldPersistence.class)
	protected FormSendRecordFieldPersistence formSendRecordFieldPersistence;
	@BeanReference(type = eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldSignalementLocalService.class)
	protected eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldSignalementLocalService formSendRecordFieldSignalementLocalService;
	@BeanReference(type = eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldSignalementService.class)
	protected eu.strasbourg.service.formSendRecordField.service.FormSendRecordFieldSignalementService formSendRecordFieldSignalementService;
	@BeanReference(type = FormSendRecordFieldSignalementPersistence.class)
	protected FormSendRecordFieldSignalementPersistence formSendRecordFieldSignalementPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = com.liferay.asset.kernel.service.AssetEntryLocalService.class)
	protected com.liferay.asset.kernel.service.AssetEntryLocalService assetEntryLocalService;
	@ServiceReference(type = com.liferay.asset.kernel.service.AssetEntryService.class)
	protected com.liferay.asset.kernel.service.AssetEntryService assetEntryService;
	@ServiceReference(type = AssetEntryPersistence.class)
	protected AssetEntryPersistence assetEntryPersistence;
}