/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.objtp.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ObjectCategory service. Represents a row in the &quot;objtp_ObjectCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link eu.strasbourg.service.objtp.model.impl.ObjectCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link eu.strasbourg.service.objtp.model.impl.ObjectCategoryImpl}.
 * </p>
 *
 * @author JeremyZwickert
 * @see ObjectCategory
 * @see eu.strasbourg.service.objtp.model.impl.ObjectCategoryImpl
 * @see eu.strasbourg.service.objtp.model.impl.ObjectCategoryModelImpl
 * @generated
 */
@ProviderType
public interface ObjectCategoryModel extends BaseModel<ObjectCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a object category model instance should use the {@link ObjectCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this object category.
	 *
	 * @return the primary key of this object category
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this object category.
	 *
	 * @param primaryKey the primary key of this object category
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the code of this object category.
	 *
	 * @return the code of this object category
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this object category.
	 *
	 * @param code the code of this object category
	 */
	public void setCode(String code);

	/**
	 * Returns the name of this object category.
	 *
	 * @return the name of this object category
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this object category.
	 *
	 * @param name the name of this object category
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		eu.strasbourg.service.objtp.model.ObjectCategory objectCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<eu.strasbourg.service.objtp.model.ObjectCategory> toCacheModel();

	@Override
	public eu.strasbourg.service.objtp.model.ObjectCategory toEscapedModel();

	@Override
	public eu.strasbourg.service.objtp.model.ObjectCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}