create table official_Official (
	uuid_ VARCHAR(75) null,
	officialId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	lastPublishDate DATE null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null,
	gender INTEGER,
	lastName VARCHAR(75) null,
	firstName VARCHAR(75) null,
	thematicDelegation TEXT null,
	missions TEXT null,
	wasMinister BOOLEAN,
	contact TEXT null,
	orderDeputyMayor INTEGER,
	orderVicePresident INTEGER,
	imageId LONG
);