/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.notif.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the NatureNotif service. Represents a row in the &quot;notif_NatureNotif&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>eu.strasbourg.service.notif.model.impl.NatureNotifModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>eu.strasbourg.service.notif.model.impl.NatureNotifImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NatureNotif
 * @generated
 */
@ProviderType
public interface NatureNotifModel
	extends BaseModel<NatureNotif>, LocalizedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a nature notif model instance should use the {@link NatureNotif} interface instead.
	 */

	/**
	 * Returns the primary key of this nature notif.
	 *
	 * @return the primary key of this nature notif
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this nature notif.
	 *
	 * @param primaryKey the primary key of this nature notif
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the nature ID of this nature notif.
	 *
	 * @return the nature ID of this nature notif
	 */
	public long getNatureId();

	/**
	 * Sets the nature ID of this nature notif.
	 *
	 * @param natureId the nature ID of this nature notif
	 */
	public void setNatureId(long natureId);

	/**
	 * Returns the service ID of this nature notif.
	 *
	 * @return the service ID of this nature notif
	 */
	public long getServiceId();

	/**
	 * Sets the service ID of this nature notif.
	 *
	 * @param serviceId the service ID of this nature notif
	 */
	public void setServiceId(long serviceId);

	/**
	 * Returns the name of this nature notif.
	 *
	 * @return the name of this nature notif
	 */
	public String getName();

	/**
	 * Returns the localized name of this nature notif in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized name of this nature notif
	 */
	@AutoEscape
	public String getName(Locale locale);

	/**
	 * Returns the localized name of this nature notif in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this nature notif. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Returns the localized name of this nature notif in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized name of this nature notif
	 */
	@AutoEscape
	public String getName(String languageId);

	/**
	 * Returns the localized name of this nature notif in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this nature notif
	 */
	@AutoEscape
	public String getName(String languageId, boolean useDefault);

	@AutoEscape
	public String getNameCurrentLanguageId();

	@AutoEscape
	public String getNameCurrentValue();

	/**
	 * Returns a map of the locales and localized names of this nature notif.
	 *
	 * @return the locales and localized names of this nature notif
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this nature notif.
	 *
	 * @param name the name of this nature notif
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this nature notif in the language.
	 *
	 * @param name the localized name of this nature notif
	 * @param locale the locale of the language
	 */
	public void setName(String name, Locale locale);

	/**
	 * Sets the localized name of this nature notif in the language, and sets the default locale.
	 *
	 * @param name the localized name of this nature notif
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setName(String name, Locale locale, Locale defaultLocale);

	public void setNameCurrentLanguageId(String languageId);

	/**
	 * Sets the localized names of this nature notif from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this nature notif
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	/**
	 * Sets the localized names of this nature notif from the map of locales and localized names, and sets the default locale.
	 *
	 * @param nameMap the locales and localized names of this nature notif
	 * @param defaultLocale the default locale
	 */
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(
		eu.strasbourg.service.notif.model.NatureNotif natureNotif);

	@Override
	public int hashCode();

	@Override
	public CacheModel<eu.strasbourg.service.notif.model.NatureNotif>
		toCacheModel();

	@Override
	public eu.strasbourg.service.notif.model.NatureNotif toEscapedModel();

	@Override
	public eu.strasbourg.service.notif.model.NatureNotif toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}