/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.strasbourg.service.official.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedGroupedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Official service. Represents a row in the &quot;official_Official&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link eu.strasbourg.service.official.model.impl.OfficialModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link eu.strasbourg.service.official.model.impl.OfficialImpl}.
 * </p>
 *
 * @author AngeliqueZUNINO
 * @see Official
 * @see eu.strasbourg.service.official.model.impl.OfficialImpl
 * @see eu.strasbourg.service.official.model.impl.OfficialModelImpl
 * @generated
 */
@ProviderType
public interface OfficialModel extends BaseModel<Official>, ShardedModel,
	StagedGroupedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a official model instance should use the {@link Official} interface instead.
	 */

	/**
	 * Returns the primary key of this official.
	 *
	 * @return the primary key of this official
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this official.
	 *
	 * @param primaryKey the primary key of this official
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this official.
	 *
	 * @return the uuid of this official
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this official.
	 *
	 * @param uuid the uuid of this official
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the official ID of this official.
	 *
	 * @return the official ID of this official
	 */
	public long getOfficialId();

	/**
	 * Sets the official ID of this official.
	 *
	 * @param officialId the official ID of this official
	 */
	public void setOfficialId(long officialId);

	/**
	 * Returns the group ID of this official.
	 *
	 * @return the group ID of this official
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this official.
	 *
	 * @param groupId the group ID of this official
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this official.
	 *
	 * @return the company ID of this official
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this official.
	 *
	 * @param companyId the company ID of this official
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this official.
	 *
	 * @return the user ID of this official
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this official.
	 *
	 * @param userId the user ID of this official
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this official.
	 *
	 * @return the user uuid of this official
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this official.
	 *
	 * @param userUuid the user uuid of this official
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this official.
	 *
	 * @return the user name of this official
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this official.
	 *
	 * @param userName the user name of this official
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this official.
	 *
	 * @return the create date of this official
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this official.
	 *
	 * @param createDate the create date of this official
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this official.
	 *
	 * @return the modified date of this official
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this official.
	 *
	 * @param modifiedDate the modified date of this official
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the last publish date of this official.
	 *
	 * @return the last publish date of this official
	 */
	@Override
	public Date getLastPublishDate();

	/**
	 * Sets the last publish date of this official.
	 *
	 * @param lastPublishDate the last publish date of this official
	 */
	@Override
	public void setLastPublishDate(Date lastPublishDate);

	/**
	 * Returns the status of this official.
	 *
	 * @return the status of this official
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this official.
	 *
	 * @param status the status of this official
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this official.
	 *
	 * @return the status by user ID of this official
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this official.
	 *
	 * @param statusByUserId the status by user ID of this official
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this official.
	 *
	 * @return the status by user uuid of this official
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this official.
	 *
	 * @param statusByUserUuid the status by user uuid of this official
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this official.
	 *
	 * @return the status by user name of this official
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this official.
	 *
	 * @param statusByUserName the status by user name of this official
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this official.
	 *
	 * @return the status date of this official
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this official.
	 *
	 * @param statusDate the status date of this official
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the gender of this official.
	 *
	 * @return the gender of this official
	 */
	public int getGender();

	/**
	 * Sets the gender of this official.
	 *
	 * @param gender the gender of this official
	 */
	public void setGender(int gender);

	/**
	 * Returns the last name of this official.
	 *
	 * @return the last name of this official
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this official.
	 *
	 * @param lastName the last name of this official
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the first name of this official.
	 *
	 * @return the first name of this official
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this official.
	 *
	 * @param firstName the first name of this official
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the thematic delegation of this official.
	 *
	 * @return the thematic delegation of this official
	 */
	@AutoEscape
	public String getThematicDelegation();

	/**
	 * Sets the thematic delegation of this official.
	 *
	 * @param thematicDelegation the thematic delegation of this official
	 */
	public void setThematicDelegation(String thematicDelegation);

	/**
	 * Returns the missions of this official.
	 *
	 * @return the missions of this official
	 */
	@AutoEscape
	public String getMissions();

	/**
	 * Sets the missions of this official.
	 *
	 * @param missions the missions of this official
	 */
	public void setMissions(String missions);

	/**
	 * Returns the was minister of this official.
	 *
	 * @return the was minister of this official
	 */
	public boolean getWasMinister();

	/**
	 * Returns <code>true</code> if this official is was minister.
	 *
	 * @return <code>true</code> if this official is was minister; <code>false</code> otherwise
	 */
	public boolean isWasMinister();

	/**
	 * Sets whether this official is was minister.
	 *
	 * @param wasMinister the was minister of this official
	 */
	public void setWasMinister(boolean wasMinister);

	/**
	 * Returns the contact of this official.
	 *
	 * @return the contact of this official
	 */
	@AutoEscape
	public String getContact();

	/**
	 * Sets the contact of this official.
	 *
	 * @param contact the contact of this official
	 */
	public void setContact(String contact);

	/**
	 * Returns the image ID of this official.
	 *
	 * @return the image ID of this official
	 */
	public Long getImageId();

	/**
	 * Sets the image ID of this official.
	 *
	 * @param imageId the image ID of this official
	 */
	public void setImageId(Long imageId);

	/**
	 * Returns <code>true</code> if this official is approved.
	 *
	 * @return <code>true</code> if this official is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this official is denied.
	 *
	 * @return <code>true</code> if this official is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this official is a draft.
	 *
	 * @return <code>true</code> if this official is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this official is expired.
	 *
	 * @return <code>true</code> if this official is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this official is inactive.
	 *
	 * @return <code>true</code> if this official is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this official is incomplete.
	 *
	 * @return <code>true</code> if this official is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this official is pending.
	 *
	 * @return <code>true</code> if this official is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this official is scheduled.
	 *
	 * @return <code>true</code> if this official is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(eu.strasbourg.service.official.model.Official official);

	@Override
	public int hashCode();

	@Override
	public CacheModel<eu.strasbourg.service.official.model.Official> toCacheModel();

	@Override
	public eu.strasbourg.service.official.model.Official toEscapedModel();

	@Override
	public eu.strasbourg.service.official.model.Official toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}